export const CLUB_NAME_AR: Record<string, string> = {
  // ── England ──
  'Manchester City': 'مانشستر سيتي',
  'Manchester United': 'مانشستر يونايتد',
  'Liverpool': 'ليفربول',
  'Arsenal': 'أرسنال',
  'Chelsea': 'تشيلسي',
  'Tottenham Hotspur': 'توتنهام هوتسبير',
  'Tottenham': 'توتنهام',
  'Newcastle United': 'نيوكاسل يونايتد',
  'Newcastle': 'نيوكاسل',
  'Aston Villa': 'أستون فيلا',
  'West Ham United': 'ويست هام يونايتد',
  'West Ham': 'ويست هام',
  'Brighton': 'برايتون',
  'Brighton & Hove Albion': 'برايتون',
  'Brentford': 'برينتفورد',
  'Fulham': 'فولهام',
  'Crystal Palace': 'كريستال بالاس',
  'Everton': 'إيفرتون',
  'Nottingham Forest': 'نوتنغهام فورست',
  'Leicester City': 'ليستر سيتي',
  'Leicester': 'ليستر',
  'Leeds United': 'ليدز يونايتد',
  'Leeds': 'ليدز',
  'Wolverhampton': 'وولفرهامبتون',
  'Wolverhampton Wanderers': 'وولفرهامبتون',
  'Wolves': 'وولفز',
  'Bournemouth': 'بورنموث',
  'Southampton': 'ساوثهامبتون',
  'Ipswich Town': 'إيبسويتش تاون',
  'Burnley': 'بيرنلي',
  'Sheffield United': 'شيفيلد يونايتد',
  'Luton Town': 'لوتون تاون',
  'Watford': 'واتفورد',
  'Swansea City': 'سوانزي سيتي',
  'Stoke City': 'ستوك سيتي',
  'Sunderland': 'صندرلاند',
  'Middlesbrough': 'ميدلزبره',
  'West Bromwich Albion': 'ويست بروميتش ألبيون',
  'Blackburn Rovers': 'بلاكبيرن روفرز',
  'Queens Park Rangers': 'كوينز بارك رانجرز',
  'Millwall': 'ميلوول',
  'Coventry City': 'كوفنتري سيتي',
  // ── Spain ──
  'Real Madrid': 'ريال مدريد',
  'Barcelona': 'برشلونة',
  'FC Barcelona': 'برشلونة',
  'Atletico Madrid': 'أتلتيكو مدريد',
  'Atlético Madrid': 'أتلتيكو مدريد',
  'Sevilla': 'إشبيلية',
  'Real Sociedad': 'ريال سوسيداد',
  'Villarreal': 'فياريال',
  'Athletic Club': 'أتلتيك بيلباو',
  'Athletic Bilbao': 'أتلتيك بيلباو',
  'Valencia': 'فالنسيا',
  'Real Betis': 'ريال بيتيس',
  'Osasuna': 'أوساسونا',
  'Celta Vigo': 'سيلتا فيغو',
  'Getafe': 'خيتافي',
  'Mallorca': 'مايوركا',
  'Girona': 'خيرونا',
  'Las Palmas': 'لاس بالماس',
  'Rayo Vallecano': 'رايو فايكانو',
  'Espanyol': 'إسبانيول',
  'Alaves': 'ألافيس',
  'Deportivo Alaves': 'ألافيس',
  'Valladolid': 'بلد الوليد',
  'Granada': 'غرناطة',
  'Cadiz': 'قادش',
  // ── Germany ──
  'Bayern Munich': 'بايرن ميونخ',
  'FC Bayern München': 'بايرن ميونخ',
  'Borussia Dortmund': 'بوروسيا دورتموند',
  'BVB': 'بوروسيا دورتموند',
  'RB Leipzig': 'آر بي لايبزيغ',
  'Bayer Leverkusen': 'باير ليفركوزن',
  'Eintracht Frankfurt': 'آينتراخت فرانكفورت',
  'VfL Wolfsburg': 'فولفسبورغ',
  'Borussia Mönchengladbach': 'بوروسيا مونشنغلادباخ',
  'Borussia Monchengladbach': 'بوروسيا مونشنغلادباخ',
  'Union Berlin': 'يونيون برلين',
  '1. FC Union Berlin': 'يونيون برلين',
  'Freiburg': 'فرايبورغ',
  'SC Freiburg': 'فرايبورغ',
  'Hoffenheim': 'هوفنهايم',
  'TSG Hoffenheim': 'هوفنهايم',
  'Werder Bremen': 'فيردر بريمن',
  'SV Werder Bremen': 'فيردر بريمن',
  'Stuttgart': 'شتوتغارت',
  'VfB Stuttgart': 'شتوتغارت',
  'Augsburg': 'أوغسبورغ',
  'FC Augsburg': 'أوغسبورغ',
  'Mainz': 'ماينز',
  '1. FSV Mainz 05': 'ماينز',
  'Cologne': 'كولن',
  '1. FC Köln': 'كولن',
  'Hertha Berlin': 'هيرتا برلين',
  'Schalke 04': 'شالكه',
  'Hamburger SV': 'هامبورغ',
  // ── Italy ──
  'Inter Milan': 'إنتر ميلان',
  'Internazionale': 'إنتر ميلان',
  'Inter': 'إنتر ميلان',
  'AC Milan': 'ميلان',
  'Milan': 'ميلان',
  'Juventus': 'يوفنتوس',
  'Napoli': 'نابولي',
  'SSC Napoli': 'نابولي',
  'Roma': 'روما',
  'AS Roma': 'روما',
  'Lazio': 'لاتسيو',
  'SS Lazio': 'لاتسيو',
  'Atalanta': 'أتالانتا',
  'Fiorentina': 'فيورنتينا',
  'ACF Fiorentina': 'فيورنتينا',
  'Torino': 'تورينو',
  'FC Torino': 'تورينو',
  'Udinese': 'أودينيزي',
  'Bologna': 'بولونيا',
  'FC Bologna': 'بولونيا',
  'Monza': 'مونزا',
  'AC Monza': 'مونزا',
  'Sassuolo': 'ساسولو',
  'Empoli': 'إمبولي',
  'Salernitana': 'ساليرنيتانا',
  'Lecce': 'ليتشي',
  'Frosinone': 'فروزينوني',
  'Cagliari': 'كالياري',
  'Hellas Verona': 'هيلاس فيرونا',
  'Venezia': 'فينيسيا',
  'Genoa': 'جنوة',
  'Sampdoria': 'سامبدوريا',
  // ── France ──
  'Paris Saint-Germain': 'باريس سان جيرمان',
  'PSG': 'باريس سان جيرمان',
  'Olympique de Marseille': 'أولمبيك مرسيليا',
  'Marseille': 'مرسيليا',
  'Monaco': 'موناكو',
  'AS Monaco': 'موناكو',
  'Olympique Lyonnais': 'أولمبيك ليون',
  'Lyon': 'ليون',
  'Lille': 'ليل',
  'LOSC Lille': 'ليل',
  'Nice': 'نيس',
  'OGC Nice': 'نيس',
  'Rennes': 'رين',
  'Stade Rennais': 'رين',
  'Lens': 'لانس',
  'RC Lens': 'لانس',
  'Strasbourg': 'ستراسبورغ',
  'Montpellier': 'مونبلييه',
  'Nantes': 'نانت',
  'FC Nantes': 'نانت',
  'Brest': 'بريست',
  'Reims': 'ريمس',
  'Bordeaux': 'بوردو',
  'Saint-Etienne': 'سان إيتيان',
  'Toulouse': 'تولوز',
  'Le Havre': 'لو هافر',
  'Angers': 'أنجيه',
  'Metz': 'ميتز',
  'Clermont Foot': 'كليرمون فوت',
  // ── Portugal ──
  'Benfica': 'بنفيكا',
  'SL Benfica': 'بنفيكا',
  'Porto': 'بورتو',
  'FC Porto': 'بورتو',
  'Sporting CP': 'سبورتينغ لشبونة',
  'Sporting Lisbon': 'سبورتينغ لشبونة',
  'Braga': 'براغا',
  'SC Braga': 'براغا',
  'Vitoria Guimaraes': 'فيتوريا غيماراس',
  // ── Netherlands ──
  'Ajax': 'أياكس',
  'AFC Ajax': 'أياكس',
  'PSV Eindhoven': 'باي إس في أيندهوفن',
  'PSV': 'باي إس في',
  'Feyenoord': 'فيينورد',
  'AZ Alkmaar': 'إيه زد',
  'AZ': 'إيه زد',
  'Utrecht': 'أوتريخت',
  'FC Utrecht': 'أوتريخت',
  'Twente': 'تفينتي',
  'FC Twente': 'تفينتي',
  'Vitesse': 'فيتيس',
  // ── Belgium ──
  'Club Brugge': 'كلوب بروج',
  'RSC Anderlecht': 'أندرلخت',
  'Anderlecht': 'أندرلخت',
  'Genk': 'خينك',
  'KRC Genk': 'خينك',
  'Gent': 'خنت',
  'KAA Gent': 'خنت',
  // ── Turkey ──
  'Galatasaray': 'غلطة سراي',
  'Fenerbahce': 'فنربخشة',
  'Fenerbahçe': 'فنربخشة',
  'Besiktas': 'بيشيكتاش',
  'Beşiktaş': 'بيشيكتاش',
  'Trabzonspor': 'طرابزون سبور',
  'Basaksehir': 'باشاكشهير',
  'Istanbul Basaksehir': 'باشاكشهير',
  // ── Scotland ──
  'Celtic': 'سيلتيك',
  'Rangers': 'رينجرز',
  // ── Austria ──
  'Red Bull Salzburg': 'ريد بول سالزبورغ',
  'RB Salzburg': 'ريد بول سالزبورغ',
  // ── Ukraine ──
  'Shakhtar Donetsk': 'شاختار دونيتسك',
  'Dynamo Kyiv': 'دينامو كييف',
  // ── Croatia ──
  'Dinamo Zagreb': 'دينامو زغرب',
  'GNK Dinamo Zagreb': 'دينامو زغرب',
  'Hajduk Split': 'هايدوك سبليت',
  // ── Greece ──
  'Olympiacos': 'أوليمبياكوس',
  'PAOK': 'باوك',
  'Panathinaikos': 'باناثينايكوس',
  // ── Russia ──
  'Zenit': 'زينيت',
  'Zenit St. Petersburg': 'زينيت سانت بطرسبرغ',
  'Spartak Moscow': 'سبارتاك موسكو',
  'CSKA Moscow': 'سيسكا موسكو',
  'Lokomotiv Moscow': 'لوكوموتيف موسكو',
  'Dynamo Moscow': 'دينامو موسكو',
  // ── Saudi Arabia ──
  'Al Hilal': 'الهلال',
  'Al-Hilal': 'الهلال',
  'Al Nassr': 'النصر',
  'Al-Nassr': 'النصر',
  'Al Ahli': 'الأهلي',
  'Al-Ahli': 'الأهلي',
  'Al Ittihad': 'الاتحاد',
  'Al-Ittihad': 'الاتحاد',
  'Al Qadsiah': 'القادسية',
  'Al-Qadsiah': 'القادسية',
  'Al Shabab': 'الشباب',
  'Al-Shabab': 'الشباب',
  'Al Faisaly': 'الفيصلي',
  'Al-Faisaly': 'الفيصلي',
  'Damac': 'ضمك',
  'DAMAC': 'ضمك',
  'Al Ettifaq': 'الاتفاق',
  'Al-Ettifaq': 'الاتفاق',
  'Al Fateh': 'الفتح',
  'Al-Fateh': 'الفتح',
  'Al Taawon': 'التعاون',
  'Al-Taawon': 'التعاون',
  'Al Khaleej': 'الخليج',
  'Al-Khaleej': 'الخليج',
  'Al Hazem': 'الحزم',
  'Al-Hazem': 'الحزم',
  'Al Riyadh': 'الرياض',
  'Al-Riyadh': 'الرياض',
  'Abha': 'أبها',
  'Al Wahda': 'الوحدة',
  'Al-Wahda': 'الوحدة',
  'Al Akhdoud': 'الأخدود',
  // ── UAE ──
  'Al Ain': 'العين',
  'Al-Ain': 'العين',
  'Al Jazira': 'الجزيرة',
  'Al-Jazira': 'الجزيرة',
  'Sharjah': 'الشارقة',
  'Al Sharjah': 'الشارقة',
  'Emirates Club': 'نادي الإمارات',
  'Bani Yas': 'بني ياس',
  'Shabab Al-Ahli': 'شباب الأهلي',
  'Al Nasr': 'النصر',
  // ── Qatar ──
  'Al Sadd': 'السد',
  'Al-Sadd': 'السد',
  'Al Duhail': 'الدحيل',
  'Al-Duhail': 'الدحيل',
  'Al Rayyan': 'الريان',
  'Al-Rayyan': 'الريان',
  'Al Wakrah': 'الوكرة',
  'Al-Wakrah': 'الوكرة',
  'Al Arabi': 'العربي',
  'Al-Arabi': 'العربي',
  'Qatar SC': 'قطر',
  'Umm Salal': 'أم صلال',
  'Al Markhiya': 'المرخية',
  'Al Gharafa': 'الغرافة',
  'Al-Gharafa': 'الغرافة',
  // ── Jordan ──
  'Al Wehdat': 'الوحدات',
  'Al-Wehdat': 'الوحدات',
  'Al Faisali': 'الفيصلي',
  'Al-Faisali': 'الفيصلي',
  'Al Jazeera': 'الجزيرة',
  'Al-Jazeera': 'الجزيرة',
  'Al Ramtha': 'الرمثا',
  'Al-Ramtha': 'الرمثا',
  'Shabab Al Ordon': 'شباب الأردن',
  'Al Hussein': 'الحسين',
  'Al Ahli Amman': 'الأهلي عمان',
  'Ma\'an': 'معان',
  // ── Egypt ──
  'Al Ahly': 'الأهلي',
  'Al-Ahly': 'الأهلي',
  'Zamalek': 'الزمالك',
  'Pyramids FC': 'بيراميدز',
  'Smouha': 'سموحة',
  'Ismaily': 'الإسماعيلي',
  'El Gouna': 'الجونة',
  // ── Morocco ──
  'Wydad Casablanca': 'الوداد الرياضي',
  'Raja Casablanca': 'الرجاء الرياضي',
  'FUS Rabat': 'الفتح الرباطي',
  'RS Berkane': 'بركان',
  // ── Tunisia ──
  'Espérance Sportive de Tunis': 'الترجي التونسي',
  'Club Africain': 'النادي الأفريقي',
  // ── Algeria ──
  'Mouloudia Club d\'Alger': 'مولودية الجزائر',
  'USM Alger': 'اتحاد العاصمة',
  // ── Iraq ──
  'Air Force Club': 'نادي القوة الجوية',
  'Al Shorta': 'الشرطة',
  'Al Zawraa': 'الزوراء',
  'Al Quwa Al Jawiya': 'القوة الجوية',
  'Erbil SC': 'أربيل',
  'Al Naft': 'النفط',
  'Duhok': 'دهوك',
  // ── MLS (USA & Canada) ──
  'Inter Miami': 'إنتر ميامي',
  'Inter Miami CF': 'إنتر ميامي',
  'LA Galaxy': 'لوس أنجلوس غالاكسي',
  'Los Angeles Galaxy': 'لوس أنجلوس غالاكسي',
  'Los Angeles FC': 'لوس أنجلوس إف سي',
  'LAFC': 'لوس أنجلوس إف سي',
  'New York City FC': 'نيويورك سيتي',
  'NYCFC': 'نيويورك سيتي',
  'New York Red Bulls': 'نيويورك ريد بولز',
  'Atlanta United': 'أتلانتا يونايتد',
  'Seattle Sounders': 'سياتل ساوندرز',
  'Seattle Sounders FC': 'سياتل ساوندرز',
  'Portland Timbers': 'بورتلاند تيمبرز',
  'Toronto FC': 'تورنتو',
  'CF Montreal': 'مونتريال',
  'Columbus Crew': 'كولومبوس كرو',
  'New England Revolution': 'نيو إنغلاند',
  'FC Dallas': 'فورت وورث',
  'Houston Dynamo': 'هيوستن دينامو',
  'Colorado Rapids': 'كولورادو رابيدز',
  'San Jose Earthquakes': 'سان خوسيه',
  'DC United': 'واشنطن',
  'Austin FC': 'أوستن',
  'Charlotte FC': 'شارلوت',
  'Nashville SC': 'ناشفيل',
  'Philadelphia Union': 'فيلادلفيا',
  'Minnesota United': 'مينيسوتا',
  'Vancouver Whitecaps': 'فانكوفر',
  'Real Salt Lake': 'ريال سولت ليك',
  'FC Cincinnati': 'سينسيناتي',
  'St. Louis City': 'سانت لويس',
  'St. Louis City SC': 'سانت لويس',
  'Orlando City': 'أورلاندو',
  'Orlando City SC': 'أورلاندو',
  'Chicago Fire': 'شيكاغو',
  'Chicago Fire FC': 'شيكاغو',
  'Sporting Kansas City': 'كانساس سيتي',
  'Earthquakes': 'سان خوسيه',
  'San Diego FC': 'سان دييغو',
  // ── Canada ──
  'Vancouver Whitecaps FC': 'فانكوفر',
  'CF Montréal': 'مونتريال',
  // ── Mexico ──
  'Club America': 'نادي أمريكا',
  'América': 'أمريكا',
  'Chivas': 'تشيفاس',
  'Guadalajara': 'غوادالاخارا',
  'Cruz Azul': 'كروز أزول',
  'Pumas UNAM': 'بوماس',
  'Tigres UANL': 'تيغريس',
  'Monterrey': 'مونتيري',
  'UANL': 'تيغريس',
  'Atlas': 'أطلس',
  'León': 'ليون',
  'Toluca': 'تولوكا',
  'Santos Laguna': 'سانتوس',
  'Necaxa': 'نيكاكسا',
  'Pachuca': 'باتشوكا',
  'Club Tijuana': 'تيخوانا',
  'Puebla': 'بويبلا',
  'Mazatlán': 'مازاتلان',
  // ── Brazil ──
  'Flamengo': 'فلامنغو',
  'Fluminense': 'فلومينينسي',
  'Palmeiras': 'بالميراس',
  'São Paulo': 'ساو باولو',
  'Corinthians': 'كورينثيانس',
  'Grêmio': 'غريميو',
  'Internacional': 'إنترناسيونال',
  'Santos': 'سانتوس',
  'Atletico Mineiro': 'أتلتيكو مينيرو',
  'Atlético Mineiro': 'أتلتيكو مينيرو',
  'Vasco da Gama': 'فاسكو دا غاما',
  'Botafogo': 'بوتافوغو',
  'Cruzeiro': 'كروزيرو',
  // ── Argentina ──
  'Boca Juniors': 'بوكا جونيورز',
  'River Plate': 'ريفر بليت',
  'Racing Club': 'راسينغ كلوب',
  'San Lorenzo': 'سان لورينزو',
  'Independiente': 'إنديبندينتي',
  'Estudiantes': 'إستوديانتيس',
  'Vélez Sársfield': 'فيليز سارسفيلد',
  'Talleres': 'تاليريس',
  // ── Colombia ──
  'Atletico Nacional': 'أتلتيكو ناسيونال',
  'Millonarios': 'ميونيريوس',
  'Junior': 'خونيور',
  // ── Japan ──
  'Urawa Red Diamonds': 'أوراوا ريد دايموندز',
  'Gamba Osaka': 'غامبا أوساكا',
  'Vissel Kobe': 'فيسيل كوبي',
  'Kashima Antlers': 'كاشيما أنتلرز',
  'Kawasaki Frontale': 'كاواساكي فرونتالي',
  'Nagoya Grampus': 'ناغويا غرامبوس',
  'Cerezo Osaka': 'سيريزو أوساكا',
  'Yokohama F. Marinos': 'يوكوهاما مارينوس',
  'Sanfrecce Hiroshima': 'سانفريتشي هيروشيما',
  // ── South Korea ──
  'Jeonbuk': 'جيونبوك',
  'Jeonbuk Hyundai Motors': 'جيونبوك',
  'Ulsan': 'أولسان',
  'Ulsan HD': 'أولسان',
  'FC Seoul': 'سيول',
  'Suwon Samsung Bluewings': 'سوون',
  // ── Australia ──
  'Melbourne City': 'ملبورن سيتي',
  'Sydney FC': 'سيدني',
  'Western Sydney Wanderers': 'ويسترن سيدني',
  // ── Iran ──
  'Persepolis': 'بيرسيبوليس',
  'Esteghlal': 'إستقلال',
  'Sepahan': 'سباهان',
  // ── China ──
  'Shanghai Port': 'شنغهاي بورت',
  'Shandong Taishan': 'شاندونغ تايشان',
  'Guangzhou FC': 'غوانغجو',
  'Beijing Guoan': 'بكين',
  // ── Free agent ──
  'Free Agent': 'وكيل حر',
};

export function getClubNameAr(name: string | null | undefined): string | null {
  if (!name) return null;
  return CLUB_NAME_AR[name] ?? null;
}
