export const NATIONALITY_AR: Record<string, string> = {
  // Americas
  'Argentine': 'أرجنتيني',
  'Argentinian': 'أرجنتيني',
  'Brazilian': 'برازيلي',
  'Uruguayan': 'أوروغواياني',
  'Colombian': 'كولومبي',
  'Ecuadorian': 'إكوادوري',
  'Paraguayan': 'باراغوياني',
  'Chilean': 'تشيلياني',
  'Venezuelan': 'فنزويلي',
  'Bolivian': 'بوليفي',
  'Peruvian': 'بيروفي',
  'American': 'أمريكي',
  'Mexican': 'مكسيكي',
  'Canadian': 'كندي',
  'Jamaican': 'جامايكي',
  'Honduran': 'هندوراسي',
  'Panamanian': 'بنمي',
  'Costa Rican': 'كوستاريكي',
  'Guatemalan': 'غواتيمالي',
  'Salvadoran': 'سلفادوري',
  'Trinidad and Tobago': 'ترينيدادي',
  // Europe
  'French': 'فرنسي',
  'German': 'ألماني',
  'Spanish': 'إسباني',
  'English': 'إنجليزي',
  'Portuguese': 'برتغالي',
  'Dutch': 'هولندي',
  'Belgian': 'بلجيكي',
  'Italian': 'إيطالي',
  'Croatian': 'كرواتي',
  'Swiss': 'سويسري',
  'Danish': 'دنماركي',
  'Swedish': 'سويدي',
  'Norwegian': 'نرويجي',
  'Polish': 'بولندي',
  'Austrian': 'نمساوي',
  'Serbian': 'صربي',
  'Ukrainian': 'أوكراني',
  'Scottish': 'اسكتلندي',
  'Welsh': 'ويلزي',
  'Turkish': 'تركي',
  'Hungarian': 'مجري',
  'Slovak': 'سلوفاكي',
  'Slovenian': 'سلوفيني',
  'Czech': 'تشيكي',
  'Greek': 'يوناني',
  'Albanian': 'ألباني',
  'Romanian': 'روماني',
  'Bulgarian': 'بلغاري',
  'Finnish': 'فنلندي',
  'Icelandic': 'آيسلندي',
  'Georgian': 'جورجي',
  'Kosovar': 'كوسوفي',
  'Israeli': 'إسرائيلي',
  // Africa
  'Moroccan': 'مغربي',
  'Senegalese': 'سنغالي',
  'Nigerian': 'نيجيري',
  'Cameroonian': 'كاميروني',
  'Ivorian': 'عاجي',
  'Ghanaian': 'غاني',
  'Egyptian': 'مصري',
  'Tunisian': 'تونسي',
  'Algerian': 'جزائري',
  'South African': 'جنوب أفريقي',
  'Congolese': 'كونغولي',
  'Malian': 'مالي',
  'Beninese': 'بنيني',
  'Guinean': 'غيني',
  'Gambian': 'غامبي',
  'Ethiopian': 'إثيوبي',
  'Gabonese': 'غابوني',
  'Tanzanian': 'تنزاني',
  'Zambian': 'زامبي',
  'Cape Verdean': 'رأسي أخضر',
  // Asia
  'Japanese': 'ياباني',
  'South Korean': 'كوري جنوبي',
  'Korean': 'كوري',
  'Australian': 'أسترالي',
  'Iranian': 'إيراني',
  'Saudi': 'سعودي',
  'Saudi Arabian': 'سعودي',
  'Qatari': 'قطري',
  'Jordanian': 'أردني',
  'Iraqi': 'عراقي',
  'Emirati': 'إماراتي',
  'Bahraini': 'بحريني',
  'Kuwaiti': 'كويتي',
  'Omani': 'عُماني',
  'Uzbek': 'أوزبكي',
  'Chinese': 'صيني',
  'Indonesian': 'إندونيسي',
  'Vietnamese': 'فيتنامي',
  'Thai': 'تايلاندي',
  // Oceania
  'New Zealander': 'نيوزيلندي',
  'New Zealand': 'نيوزيلندي',
};

export function getNationalityAr(nationality: string | null | undefined): string | null {
  if (!nationality) return null;
  return NATIONALITY_AR[nationality] ?? null;
}
