// Arabic display names keyed by the English name returned by api-football.
// Accented and non-accented variants are both included where the API varies.
export const PLAYER_NAMES_AR: Record<string, string> = {

  // ── Head Coaches — WC 2026 ────────────────────────────────────────────────────
  // CONMEBOL
  'Lionel Scaloni':       'ليونيل سكالوني',
  'Carlo Ancelotti':      'كارلو أنشيلوتي',
  'Nestor Lorenzo':       'نيستور لورينثو',
  'Néstor Lorenzo':       'نيستور لورينثو',
  'Sebastian Beccacece':  'سيباستيان بيكاسيتشي',
  'Sebastián Beccacece':  'سيباستيان بيكاسيتشي',
  'Gustavo Alfaro':       'غوستافو ألفارو',
  'Marcelo Bielsa':       'مارسيلو بييلسا',
  // CONCACAF
  'Jesse Marsch':         'جيسي مارش',
  'Dick Advocaat':        'ديك أدفوكات',
  'Sebastien Migne':      'سيباستيان مينيه',
  'Sébastien Migné':      'سيباستيان مينيه',
  'Javier Aguirre':       'هافيير أغيري',
  'Thomas Christiansen':  'توماس كريستيانسن',
  'Mauricio Pochettino':  'ماوريسيو بوتشيتينو',
  // UEFA
  'Ralf Rangnick':        'رالف رانغنيك',
  'Rudi Garcia':          'رودي غارسيا',
  'Sergej Barbarez':      'سيرغي بارباريز',
  'Zlatko Dalic':         'زلاتكو داليتش',
  'Zlatko Dalić':         'زلاتكو داليتش',
  'Miroslav Koubek':      'ميروسلاف كوبيك',
  'Thomas Tuchel':        'توماس توخيل',
  'Didier Deschamps':     'ديدييه ديشان',
  'Julian Nagelsmann':    'يوليان ناغلسمان',
  'Ronald Koeman':        'رونالد كويمان',
  'Stale Solbakken':      'ستوله سولباكن',
  'Ståle Solbakken':      'ستوله سولباكن',
  'Roberto Martinez':     'روبيرتو مارتينيز',
  'Roberto Martínez':     'روبيرتو مارتينيز',
  'Steve Clarke':         'ستيف كلارك',
  'Luis de la Fuente':    'لويس دي لا فوينتي',
  'Graham Potter':        'غراهام بوتر',
  'Murat Yakin':          'مورات ياكين',
  'Vincenzo Montella':    'فينشنزو مونتيلا',
  // CAF
  'Bubista':              'بوبيستا',
  'Sebastien Desabre':    'سيباستيان ديزابر',
  'Sébastien Desabre':    'سيباستيان ديزابر',
  'Carlos Queiroz':       'كارلوس كيروش',
  'Emerse Fae':           'إيمرس فاي',
  'Emerse Faé':           'إيمرس فاي',
  'Pape Thiaw':           'باب تياو',
  'Hugo Broos':           'هوغو بروس',
  // AFC
  'Tony Popovic':         'توني بوبوفيتش',
  'Amir Ghalenoei':       'أمير قلعة نوي',
  'Hajime Moriyasu':      'هاجيمي موريياسو',
  'Hong Myung-bo':        'هونغ مايونغ بو',
  'Fabio Cannavaro':      'فابيو كانافارو',
  // OFC
  'Darren Bazeley':       'داريان بازلي',
  // Arab teams — verified correct coaches
  'Graham Arnold':        'غراهام أرنولد',
  'Georgios Donis':       'جورجيوس دونيس',
  'G. Donis':             'جورجيوس دونيس',
  'Mohamed Ouahbi':       'محمد وهبي',

  // ── France ───────────────────────────────────────────────────────────────────
  'Kylian Mbappe': 'كيليان مبابي',
  'Kylian Mbappé': 'كيليان مبابي',
  'Antoine Griezmann': 'أنطوان غريزمان',
  'Ousmane Dembele': 'أوسمان ديمبيلي',
  'Ousmane Dembélé': 'أوسمان ديمبيلي',
  'Kingsley Coman': 'كينغسلي كومان',
  'Eduardo Camavinga': 'إدواردو كاموانغا',
  'Aurelien Tchouameni': 'أوريليان تشواميني',
  'Aurélien Tchouaméni': 'أوريليان تشواميني',
  'Adrien Rabiot': 'أدريان رابيو',
  'Jules Kounde': 'جول كونديه',
  'Jules Koundé': 'جول كونديه',
  'Dayot Upamecano': 'داييو أوباميكانو',
  'Mike Maignan': 'مايك مانيان',
  'Hugo Lloris': 'هيغو يوريس',
  'Marcus Thuram': 'ماركوس توران',
  'Randal Kolo Muani': 'راندال كولو مواني',
  'Warren Zaire-Emery': 'وارن زاير إيميري',
  'William Saliba': 'ويليام ساليبا',
  'Theo Hernandez': 'تيو هيرنانديز',
  'Théo Hernandez': 'تيو هيرنانديز',
  'Lucas Hernandez': 'لوكاس هيرنانديز',
  'Lucas Hernández': 'لوكاس هيرنانديز',
  'Benjamin Pavard': 'بنجامان بافار',
  'N\'Golo Kante': 'نغولو كانتي',
  "N'Golo Kanté": 'نغولو كانتي',
  'Paul Pogba': 'بول بوغبا',
  'Karim Benzema': 'كريم بنزيمة',
  'Olivier Giroud': 'أوليفييه جيرو',
  'Raphael Varane': 'رافاييل فاران',
  'Raphaël Varane': 'رافاييل فاران',
  'Presnel Kimpembe': 'بريسنيل كيمبيمبي',
  'Ibrahima Konate': 'إبراهيما كوناتي',
  'Ibrahima Konaté': 'إبراهيما كوناتي',
  'Christopher Nkunku': 'كريستوفر نكونكو',
  'Matthieu Guendouzi': 'ماتيو غندوزي',
  'Corentin Tolisso': 'كورانتان توليسو',
  'Steve Mandanda': 'ستيف ماندندا',
  'Alphonse Areola': 'ألفونس أريولا',
  'Wissam Ben Yedder': 'وسام بن يدر',

  // ── Brazil ───────────────────────────────────────────────────────────────────
  'Vinicius Junior': 'فينيسيوس جونيور',
  'Rodrygo': 'رودريغو',
  'Rodrygo Goes': 'رودريغو غويش',
  'Neymar': 'نيمار',
  'Neymar Jr': 'نيمار',
  'Casemiro': 'كاسيميرو',
  'Alisson': 'أليسون',
  'Alisson Becker': 'أليسون بيكر',
  'Marquinhos': 'ماركينيوس',
  'Thiago Silva': 'تياغو سيلفا',
  'Gabriel Martinelli': 'غابرييل مارتينيلي',
  'Richarlison': 'ريتشارليسون',
  'Antony': 'أنتوني',
  'Lucas Paqueta': 'لوكاس باكيتا',
  'Lucas Paquetá': 'لوكاس باكيتا',
  'Raphinha': 'رافينيا',
  'Eder Militao': 'إيدير ميليتاو',
  'Éder Militão': 'إيدير ميليتاو',
  'Gabriel Magalhaes': 'غابرييل ماغالياييس',
  'Gabriel Magalhães': 'غابرييل ماغالياييس',
  'Danilo': 'دانيلو',
  'Alex Sandro': 'أليكس ساندرو',
  'Fred': 'فريد',
  'Bruno Guimaraes': 'برونو غيماريش',
  'Bruno Guimarães': 'برونو غيماريش',
  'Endrick': 'إندريك',
  'Savinho': 'سافينيو',
  'Gabriel Jesus': 'غابرييل جيسوس',
  'Firmino': 'فيرمينو',
  'Roberto Firmino': 'روبرتو فيرمينو',
  'Ederson': 'إيدرسون',
  'Alex Telles': 'أليكس تيليش',
  'Fabinho': 'فابينيو',
  'Allan': 'ألان',
  'Gerson': 'جيرسون',
  'Evanilson': 'إيفانيلسون',
  'Dudu': 'دودو',
  'Igor Jesus': 'إيغور جيسوس',
  'Weverton': 'ويفيرتون',
  'Bremer': 'بريمير',
  'Gleison Bremer': 'بريمير',
  'Roger Ibanez': 'روجر إيبانيز',
  'Roger Ibañez': 'روجر إيبانيز',
  'Douglas Santos': 'دوغلاس سانتوس',
  'Danilo Santos': 'دانيلو سانتوس',
  'Luiz Henrique': 'لويز إنريكي',
  'Igor Thiago': 'إيغور تياغو',
  'Matheus Cunha': 'ماتيوس كونيا',
  'Rayan': 'رايان',

  // ── Argentina ────────────────────────────────────────────────────────────────
  'Lionel Messi': 'ليونيل ميسي',
  'Angel Di Maria': 'أنخيل دي ماريا',
  'Ángel Di María': 'أنخيل دي ماريا',
  'Lautaro Martinez': 'لاوتارو مارتينيز',
  'Lautaro Martínez': 'لاوتارو مارتينيز',
  'Alexis Mac Allister': 'أليكسيس ماك أليستر',
  'Rodrigo De Paul': 'رودريغو دي بول',
  'Emiliano Martinez': 'إميليانو مارتينيز',
  'Emiliano Martínez': 'إميليانو مارتينيز',
  'Cristian Romero': 'كريستيان روميرو',
  'Nahuel Molina': 'ناهويل مولينا',
  'Nicolas Otamendi': 'نيكولاس أوتامندي',
  'Nicolás Otamendi': 'نيكولاس أوتامندي',
  'Enzo Fernandez': 'إنزو فيرنانديز',
  'Enzo Fernández': 'إنزو فيرنانديز',
  'Julian Alvarez': 'خوليان ألفاريز',
  'Julián Álvarez': 'خوليان ألفاريز',
  'Paulo Dybala': 'باولو ديبالا',
  'Leandro Paredes': 'ليانرو باريديس',
  'Marcos Acuna': 'ماركوس أكونيا',
  'Marcos Acuña': 'ماركوس أكونيا',
  'Angel Correa': 'أنخيل كوريا',
  'Ángel Correa': 'أنخيل كوريا',
  'Giovani Lo Celso': 'خيوفاني لو سيلسو',
  'Nicolas Tagliafico': 'نيكولاس تاليافيكو',
  'Nicolás Tagliafico': 'نيكولاس تاليافيكو',
  'Guido Rodriguez': 'غيدو رودريغيز',
  'Guido Rodríguez': 'غيدو رودريغيز',
  'German Pezzella': 'خيرمان بيثيلا',
  'Germán Pezzella': 'خيرمان بيثيلا',
  'Walter Benitez': 'والتر بينيتيز',

  // ── England ──────────────────────────────────────────────────────────────────
  'Harry Kane': 'هاري كين',
  'Jude Bellingham': 'جود بيلينغهام',
  'Bukayo Saka': 'بوكايو ساكا',
  'Marcus Rashford': 'ماركوس راشفورد',
  'Phil Foden': 'فيل فودن',
  'Harry Maguire': 'هاري ماغواير',
  'Kyle Walker': 'كايل ووكر',
  'Jordan Pickford': 'جوردان بيكفورد',
  'Mason Mount': 'ماسون ماونت',
  'Trent Alexander-Arnold': 'ترينت ألكسندر-أرنولد',
  'Luke Shaw': 'لوك شو',
  'Declan Rice': 'ديكلان رايس',
  'Jordan Henderson': 'جوردان هندرسون',
  'Raheem Sterling': 'رحيم ستيرلينغ',
  'John Stones': 'جون ستونز',
  'Conor Gallagher': 'كونور غالاغر',
  'Jarrod Bowen': 'جارود بوين',
  'Nick Pope': 'نيك بوب',
  'Jack Grealish': 'جاك غريليش',
  'Ollie Watkins': 'أولي ووتكينز',
  'Cole Palmer': 'كول بالمر',
  'Kobbie Mainoo': 'كوبي مانو',
  'Levi Colwill': 'ليفي كولويل',
  'Ezri Konsa': 'إيزري كونسا',
  'Joe Gomez': 'جو غوميز',
  'Kalvin Phillips': 'كالفين فيليبس',
  'Anthony Gordon': 'أنتوني غوردون',
  'Eberechi Eze': 'إيبيريتشي إيزي',
  'Ivan Toney': 'إيفان توني',
  'Kieran Trippier': 'كيران تريبير',
  'James Maddison': 'جيمس ماديسون',
  'Aaron Ramsdale': 'آرون رامسديل',
  'Ben Chilwell': 'بن تشيلويل',

  // ── Spain ────────────────────────────────────────────────────────────────────
  'Pedri': 'بيدري',
  'Pedri Gonzalez': 'بيدري غونثاليز',
  'Pedri González': 'بيدري غونثاليز',
  'Gavi': 'غافي',
  'Lamine Yamal': 'لامين يامال',
  'Ferran Torres': 'فيران توريس',
  'Alvaro Morata': 'ألفارو موراتا',
  'Álvaro Morata': 'ألفارو موراتا',
  'Rodri': 'رودري',
  'Dani Carvajal': 'داني كارباخال',
  'Jordi Alba': 'خوردي ألبا',
  'David De Gea': 'دافيد دي خيا',
  'Unai Simon': 'أوناي سيمون',
  'Unai Simón': 'أوناي سيمون',
  'Aymeric Laporte': 'إيميريك لابورتي',
  'Marc Cucurella': 'مارك كوكوريلا',
  'Alejandro Balde': 'أليخاندرو بالدي',
  'Alejandro Baldé': 'أليخاندرو بالدي',
  'Marco Asensio': 'ماركو أسينسيو',
  'Dani Olmo': 'داني أولمو',
  'Fabian Ruiz': 'فابيان رويز',
  'Fabián Ruiz': 'فابيان رويز',
  'Mikel Merino': 'ميكيل مورينو',
  'Joselu': 'خوسيلو',
  'Yeremy Pino': 'يريمي بينو',
  'Nico Williams': 'نيكو ويليامز',
  'Robin Le Normand': 'روبان لو نورمان',
  'Pau Cubarsi': 'باو كوبارسي',
  'Pau Cubarsí': 'باو كوبارسي',
  'Martin Zubimendi': 'مارتن زوبيمندي',
  'Martín Zubimendi': 'مارتن زوبيمندي',
  'Mikel Oyarzabal': 'ميكيل أوياثابال',
  'Pedro Porro': 'بيدرو بورو',
  'Jose Gaya': 'خوسيه غايا',
  'José Gayà': 'خوسيه غايا',

  // ── Germany ──────────────────────────────────────────────────────────────────
  'Thomas Muller': 'توماس مولر',
  'Thomas Müller': 'توماس مولر',
  'Joshua Kimmich': 'يوشوا كيميش',
  'Leon Goretzka': 'ليون غوريتسكا',
  'Kai Havertz': 'كاي هافيرتس',
  'Leroy Sane': 'لوروا ساني',
  'Leroy Sané': 'لوروا ساني',
  'Serge Gnabry': 'سيرج غنابري',
  'Antonio Rudiger': 'أنتونيو روديغر',
  'Antonio Rüdiger': 'أنتونيو روديغر',
  'Manuel Neuer': 'مانويل نوير',
  'Florian Wirtz': 'فلوريان ويرتس',
  'Jamal Musiala': 'جامال موسيالا',
  'Niklas Sule': 'نيكلاس سوله',
  'Niklas Süle': 'نيكلاس سوله',
  'Ilkay Gundogan': 'إلكاي غوندوغان',
  'Ilkay Gündogan': 'إلكاي غوندوغان',
  'Timo Werner': 'تيمو فيرنر',
  'Robin Gosens': 'روبن غوزنس',
  'Marc-Andre ter Stegen': 'ماركو-أندريه تير ستيغن',
  'Marc-André ter Stegen': 'ماركو-أندريه تير ستيغن',
  'David Raum': 'دافيد راوم',
  'Jonas Hofmann': 'يوناس هوفمان',
  'Niclas Fullkrug': 'نيكلاس فولكروغ',
  'Niclas Füllkrug': 'نيكلاس فولكروغ',
  'Pascal Gross': 'باسكال غروس',
  'Pascal Groß': 'باسكال غروس',
  'Benjamin Henrichs': 'بنجامين هنريكس',
  'Thilo Kehrer': 'تيلو كيرر',
  'Matthias Ginter': 'ماتياس غينتر',
  'Lukas Klostermann': 'لوكاس كلوسترمان',
  'Maximilian Mittelstädt': 'ماكسيميليان ميتلشتادت',
  'Chris Fuhrich': 'كريس فوريش',
  'Deniz Undav': 'دينيز أوندف',
  'Emre Can': 'إمري جان',
  'Nadiem Amiri': 'ناديم أميري',
  'Justin Leweling': 'جاستن ليفيلينغ',
  'Aleksandar Pavlovic': 'ألكسندر بافلوفيتش',
  'Nico Schlotterbeck': 'نيكو شلوتيربيك',
  'Jonathan Tah': 'يوناثان تاه',
  'Alexander Nubel': 'ألكسندر نوبل',
  'Alexander Nübel': 'ألكسندر نوبل',
  'Oliver Baumann': 'أوليفر باومان',
  'Waldemar Anton': 'فالدمار أنتون',
  'Assan Ouedraogo': 'آسان أويدراغو',
  'Assan Ouédraogo': 'آسان أويدراغو',
  'Angelo Stiller': 'أنجيلو شتيلر',
  'Maximilian Beier': 'ماكسيميليان باير',
  'Nick Woltemade': 'نيك فولتيمادي',
  'Felix Nmecha': 'فيليكس نميشا',
  'Nathaniel Brown': 'ناثانيئيل براون',

  // ── Netherlands ───────────────────────────────────────────────────────────────
  'Virgil van Dijk': 'فيرخيل فان دايك',
  'Matthijs de Ligt': 'ماتاييس دي ليخت',
  'Marten de Roon': 'مارتن دي رون',
  'Denzel Dumfries': 'دنزل دامفريس',
  'Georginio Wijnaldum': 'خيورخينيو فيينالدوم',
  'Memphis Depay': 'ميمفيس ديباي',
  'Cody Gakpo': 'كودي غاكبو',
  'Davy Klaassen': 'دافي كلاسن',
  'Steven Bergwijn': 'ستيفن بيرغفاين',
  'Daley Blind': 'دالي بلايند',
  'Jurrien Timber': 'يوريين تيمبر',
  'Nathan Ake': 'ناثان أكي',
  'Nathan Aké': 'ناثان أكي',
  'Frenkie de Jong': 'فرينكي دي يونغ',
  'Xavi Simons': 'تشافي سيمونز',
  'Wout Weghorst': 'واوت فيخورست',
  'Donyell Malen': 'دونييل مالين',
  'Teun Koopmeiners': 'تيون كوبمينرز',
  'Ryan Gravenberch': 'راين خرافينبرخ',
  'Bart Verbruggen': 'بارت فيربروخن',
  'Stefan de Vrij': 'ستيفان دي فراي',
  'Jeremie Frimpong': 'جيريمي فريمبونج',
  'Ian Maatsen': 'إيان ماتسن',

  // ── Belgium ──────────────────────────────────────────────────────────────────
  'Kevin De Bruyne': 'كيفن دي برويني',
  'Romelu Lukaku': 'روملو لوكاكو',
  'Youri Tielemans': 'يوري تيلمانس',
  'Jan Vertonghen': 'يان فيرتونغن',
  'Toby Alderweireld': 'توبي ألدرفيريلد',
  'Axel Witsel': 'أكسيل ويتسيل',
  'Jeremy Doku': 'جيريمي دوكو',
  'Jérémy Doku': 'جيريمي دوكو',
  'Leandro Trossard': 'ليوناردو تروسار',
  'Yannick Carrasco': 'يانيك كاراسكو',
  'Dries Mertens': 'دريس ميرتنس',
  'Thomas Meunier': 'توماس مونييه',
  'Timothy Castagne': 'تيموثي كاستانييه',
  'Charles De Ketelaere': 'تشارلز دي كيتيلاري',
  'Lois Openda': 'لواس أوبندا',
  'Loïs Openda': 'لواس أوبندا',
  'Arthur Theate': 'أرثور تياتي',
  'Wout Faes': 'واوت فايس',
  'Eden Hazard': 'إيدن هازار',
  'Thibaut Courtois': 'تيبو كورتوا',
  'Johan Manzambi': 'يوهان مانزامبي',

  // ── Portugal ─────────────────────────────────────────────────────────────────
  'Cristiano Ronaldo': 'كريستيانو رونالدو',
  'Bruno Fernandes': 'برونو فيرنانديز',
  'Joao Felix': 'جواو فيليكس',
  'João Félix': 'جواو فيليكس',
  'Joao Cancelo': 'جواو كانسيلو',
  'João Cancelo': 'جواو كانسيلو',
  'Pepe': 'بيبي',
  'Ruben Dias': 'روبن دياش',
  'Rúben Dias': 'روبن دياش',
  'Ruben Neves': 'روبن نيفيس',
  'Rúben Neves': 'روبن نيفيس',
  'Ricardo Horta': 'ريكاردو أورتا',
  'Rafael Leao': 'رافاييل لياو',
  'Rafael Leão': 'رافاييل لياو',
  'Bernardo Silva': 'برناردو سيلفا',
  'Pedro Neto': 'بيدرو نيتو',
  'Diogo Jota': 'دييغو خوتا',
  'Andre Silva': 'أندريه سيلفا',
  'André Silva': 'أندريه سيلفا',
  'Joao Palhinha': 'جواو بالينيا',
  'João Palhinha': 'جواو بالينيا',
  'Vitinha': 'فيتينيا',
  'Goncalo Inacio': 'غونسالو إناسيو',
  'Gonçalo Inácio': 'غونسالو إناسيو',
  'Rui Patricio': 'روي باتريسيو',
  'Rui Patrício': 'روي باتريسيو',
  'Diogo Costa': 'دييغو كوستا',
  'Goncalo Ramos': 'غونسالو راموس',
  'Gonçalo Ramos': 'غونسالو راموس',
  'Nuno Mendes': 'نونو ميندز',
  'Matheus Nunes': 'ماتيوس نونيز',
  'William Carvalho': 'ويليام كارفالهو',
  'Nelson Semedo': 'نيلسون سيميدو',
  'Danilo Pereira': 'دانيلو بيريرا',

  // ── Morocco ──────────────────────────────────────────────────────────────────
  'Achraf Hakimi': 'أشرف حكيمي',
  'Hakim Ziyech': 'حكيم زياش',
  'Youssef En-Nesyri': 'يوسف النصيري',
  'Nayef Aguerd': 'نايف أكرد',
  'Sofyan Amrabat': 'سفيان أمرابط',
  'Noussair Mazraoui': 'نصير مزراوي',
  'Romain Saiss': 'رومان سايس',
  'Romain Saïss': 'رومان سايس',
  'Sofiane Boufal': 'سفيان بوفال',
  'Azzedine Ounahi': 'عزدين أوناحي',
  'Selim Amallah': 'سليم أمالا',
  'Bono': 'بونو',
  'Yassine Bounou': 'ياسين بونو',
  'Jawad El Yamiq': 'جواد الياميق',
  'Yahia Attiyat-Allah': 'يحيى عطية الله',
  'Adam Masina': 'آدم مازينا',
  'Zakaria Aboukhlal': 'زكريا أبوخلال',
  'Abde Ezzalzouli': 'عبد الرزاق الزلزولي',
  'Youssef Ait Bennasser': 'يوسف آيت بناصر',
  'Imran Louza': 'عمران لوزا',

  // ── Japan ────────────────────────────────────────────────────────────────────
  'Takefusa Kubo': 'تاكيفوسا كوبو',
  'Kaoru Mitoma': 'كاورو ميتوما',
  'Daichi Kamada': 'دايتشي كامادا',
  'Ritsu Doan': 'ريتسو دوان',
  'Hiroki Ito': 'هيروكي إيتو',
  'Shuichi Gonda': 'شويتشي غوندا',
  'Maya Yoshida': 'مايا يوشيدا',
  'Ko Itakura': 'كو إيتاكورا',
  'Hidemasa Morita': 'هيديماسا موريتا',
  'Junya Ito': 'جونيا إيتو',
  'Wataru Endo': 'واتارو إندو',
  'Ao Tanaka': 'آو تاناكا',
  'Takumi Minamino': 'تاكومي ميناميو',
  'Yukinari Sugawara': 'يوكيناري سوغاوارا',
  'Mao Hosoya': 'ماو هوسويا',

  // ── South Korea ──────────────────────────────────────────────────────────────
  'Son Heung-min': 'سون هيونغ مين',
  'Kim Min-jae': 'كيم مين جاي',
  'Lee Kang-in': 'لي كانغ إن',
  'Hwang Hee-chan': 'هوانغ هي تشان',
  'Kim Seung-gyu': 'كيم سيونغ غيو',
  'Hwang In-beom': 'هوانغ إن بيوم',
  'Jung Woo-young': 'جونغ وو يونغ',
  'Lee Jae-sung': 'لي جاي سونغ',
  'Cho Gue-sung': 'تشو غوي سونغ',
  'Oh Hyeon-gyu': 'أو هيون غيو',
  'Lee Gi-hyuk': 'لي غي-هيوك',
  'Gi-Hyuk Lee': 'لي غي-هيوك',

  // ── United States ────────────────────────────────────────────────────────────
  'Christian Pulisic': 'كريستيان بوليسيتش',
  'Giovanni Reyna': 'خيوفاني رينا',
  'Sergino Dest': 'سيرجينيو ديست',
  'Sergiño Dest': 'سيرجينيو ديست',
  'Weston McKennie': 'ويستون ماكيني',
  'Matt Turner': 'مات تيرنر',
  'Tyler Adams': 'تايلر آدامز',
  'Tim Weah': 'تيم وييه',
  'Brenden Aaronson': 'بريندن أرنسون',
  'Josh Sargent': 'جوش سارجنت',
  'Ricardo Pepi': 'ريكاردو بيبي',
  'Folarin Balogun': 'فولارين بالوغون',
  'Yunus Musah': 'يونس موساه',
  'Reggie Cannon': 'ريجي كانون',
  'Chris Richards': 'كريس ريتشاردز',
  'Joe Scally': 'جو سكالي',
  'Cameron Carter-Vickers': 'كاميرون كارتر-فيكرز',
  'Gio Reyna': 'خيو رينا',
  'Antonee Robinson': 'أنتوني روبنسون',
  'Walker Zimmermann': 'ووكر زيمرمان',
  'Brian Gutierrez': 'برايان غوتيريز',
  'Brian Gutiérrez': 'برايان غوتيريز',

  // ── Canada ───────────────────────────────────────────────────────────────────
  'Alphonso Davies': 'ألفونسو دايفيس',
  'Jonathan David': 'جوناثان دايفيد',
  'Tajon Buchanan': 'تاجون بوكانان',
  'Mark-Anthony Kaye': 'مارك-أنتوني كاي',
  'Cyle Larin': 'سايل لارين',
  'Jonathan Osorio': 'جوناثان أوسوريو',
  'Liam Millar': 'ليام ميلار',
  'Richie Laryea': 'ريتشي لاريا',
  'Milan Borjan': 'ميلان بورهان',
  'Ismaël Koné': 'إسماعيل كوني',
  'Ismael Kone': 'إسماعيل كوني',
  'Moise Bombito': 'مويز بومبيتو',
  'Derek Cornelius': 'ديريك كورنيليوس',

  // ── Mexico ───────────────────────────────────────────────────────────────────
  'Hirving Lozano': 'هيرفينغ لوثانو',
  'Carlos Vela': 'كارلوس بيلا',
  'Hector Herrera': 'هيكتور هيريرا',
  'Héctor Herrera': 'هيكتور هيريرا',
  'Guillermo Ochoa': 'غيليرمو أوتشوا',
  'Raul Jimenez': 'راؤول خيمينيز',
  'Raúl Jiménez': 'راؤول خيمينيز',
  'Edson Alvarez': 'إيدسون ألفاريز',
  'Edson Álvarez': 'إيدسون ألفاريز',
  'Alexis Vega': 'أليكسيس بيغا',
  'Andres Guardado': 'أندريس غوارداردو',
  'Andrés Guardado': 'أندريس غوارداردو',
  'Orbelín Pineda': 'أوربيلين بينيدا',
  'Orbelin Pineda': 'أوربيلين بينيدا',
  'Santiago Gimenez': 'سانتياغو خيمينيز',
  'Santiago Giménez': 'سانتياغو خيمينيز',
  'Cesar Montes': 'سيسار مونتيس',
  'César Montes': 'سيسار مونتيس',

  // ── Senegal ──────────────────────────────────────────────────────────────────
  'Sadio Mane': 'ساديو ماني',
  'Sadio Mané': 'ساديو ماني',
  'Kalidou Koulibaly': 'كاليدو كوليبالي',
  'Ismaila Sarr': 'إسماعيلا سار',
  'Ismaïla Sarr': 'إسماعيلا سار',
  'Edouard Mendy': 'إيدوار ميندي',
  'Édouard Mendy': 'إيدوار ميندي',
  'Idrissa Gana Gueye': 'إدريسا غانا غيي',
  'Cheikhou Kouyate': 'شيخو كوياتي',
  'Cheikhou Kouyaté': 'شيخو كوياتي',
  'Boulaye Dia': 'بولاي ديا',
  'Iliman Ndiaye': 'إليمان نداي',
  'Pape Matar Sarr': 'بابي ماتار سار',
  'Nicolas Jackson': 'نيكولاس جاكسون',
  'Lamine Camara': 'لامين كامارا',

  // ── Cameroon ─────────────────────────────────────────────────────────────────
  'Andre-Frank Zambo Anguissa': 'أندريه فرانك زامبو أنغيسا',
  'André-Frank Zambo Anguissa': 'أندريه فرانك زامبو أنغيسا',
  'Vincent Aboubakar': 'فينسيان أبوبكر',
  'Karl Toko Ekambi': 'كارل توكو إيكامبي',
  'Eric Maxim Choupo-Moting': 'إيريك ماكسيم تشوبو موتينغ',
  'Jean-Charles Castelletto': 'جان تشارلز كاستيليتو',
  'Martin Hongla': 'مارتن هونغلا',
  'Harold Moukoudi': 'هارولد موكودي',
  'Devis Epassy': 'ديفيس إيباسي',
  'Tolo Nouhou': 'تولو نوهو',

  // ── Ghana ────────────────────────────────────────────────────────────────────
  'Thomas Partey': 'توماس بارتي',
  'Mohammed Kudus': 'محمد كودوس',
  'Jordan Ayew': 'جوردان أيو',
  'Andre Ayew': 'أندريه أيو',
  'André Ayew': 'أندريه أيو',
  'Antoine Semenyo': 'أنطوان سيمينيو',
  'Kamaldeen Sulemana': 'كامالدين سليمانا',
  'Mohammed Salisu': 'محمد صالح',
  'Daniel Amartey': 'دانييل أمارتي',
  'Lawrence Ati-Zigi': 'لورانس أتي زيغي',
  'Inaki Williams': 'إيناكي ويليامز',
  'Iñaki Williams': 'إيناكي ويليامز',

  // ── Ecuador ──────────────────────────────────────────────────────────────────
  'Enner Valencia': 'إينير فالنسيا',
  'Moises Caicedo': 'مويسيس كايسيدو',
  'Moisés Caicedo': 'مويسيس كايسيدو',
  'Angel Mena': 'أنخيل مينا',
  'Ángel Mena': 'أنخيل مينا',
  'Gonzalo Plata': 'غونثالو بلاتا',
  'Felix Torres': 'فيليكس توريس',
  'Félix Torres': 'فيليكس توريس',
  'Pervis Estupinan': 'بيرفيس إستوبينيان',
  'Pervis Estupiñán': 'بيرفيس إستوبينيان',
  'Jeremy Sarmiento': 'جيريمي سارميينتو',

  // ── Uruguay ──────────────────────────────────────────────────────────────────
  'Federico Valverde': 'فيديريكو فالفيردي',
  'Rodrigo Bentancur': 'رودريغو بنتانكور',
  'Giorgian de Arrascaeta': 'جيورجيان دي أراسكايتا',
  'Darwin Nunez': 'دارون نونييز',
  'Darwin Núñez': 'دارون نونييز',
  'Mathias Olivera': 'ماتياس أوليفيرا',
  'Mathías Olivera': 'ماتياس أوليفيرا',
  'Jose Maria Gimenez': 'خوسيه ماريا خيمينيز',
  'José María Giménez': 'خوسيه ماريا خيمينيز',
  'Ronald Araujo': 'رونالد أراوخو',
  'Ronald Araújo': 'رونالد أراوخو',
  'Manuel Ugarte': 'مانويل أوغارتي',
  'Facundo Pellistri': 'فاكوندو بيليستري',
  'Luis Suarez': 'لويس سواريز',
  'Luis Suárez': 'لويس سواريز',
  'Edinson Cavani': 'إيدينسون كافاني',
  'Agustin Canobbio': 'أغوستين كانوبيو',
  'Agustín Canobbio': 'أغوستين كانوبيو',

  // ── Colombia ─────────────────────────────────────────────────────────────────
  'James Rodriguez': 'خامس رودريغيز',
  'James Rodríguez': 'خامس رودريغيز',
  'Luis Diaz': 'لويس دياز',
  'Luis Díaz': 'لويس دياز',
  'Juan Cuadrado': 'خوان كوادرادو',
  'Mateus Uribe': 'ماتيوس أوريبي',
  'Luis Sinisterra': 'لويس سينيستيرا',
  'Daniel Munoz': 'دانييل مونيوز',
  'Daniel Muñoz': 'دانييل مونيوز',
  'Davinson Sanchez': 'دافينسون سانشيز',
  'Davinson Sánchez': 'دافينسون سانشيز',
  'Richard Rios': 'ريتشارد ريوس',
  'Richard Ríos': 'ريتشارد ريوس',
  'Jefferson Lerma': 'جيفرسون ليرما',
  'John Cordoba': 'جون كوردوبا',
  'John Córdoba': 'جون كوردوبا',
  'Jhon Duran': 'هون دوران',

  // ── Saudi Arabia ─────────────────────────────────────────────────────────────
  'Salem Al-Dawsari': 'سالم الدوسري',
  'Mohammed Al-Buraikan': 'محمد البريكان',
  'Mohammed Al-Owais': 'محمد العويس',
  'Ali Al-Bulayhi': 'علي البليهي',
  'Saleh Al-Shehri': 'صالح الشهري',
  'Abdullah Al-Hamdan': 'عبدالله الحمدان',
  'Mohammed Kanno': 'محمد قنو',
  'Ali Al-Hassan': 'علي الحسن',
  'Hattan Bahebri': 'حتان بحيبري',
  'Yasser Al-Shahrani': 'ياسر الشهراني',
  'Sultan Ghannam': 'سلطان الغنام',
  'Abdulelah Al-Amri': 'عبدالإله العمري',
  'Hassan Al-Tambakti': 'حسن التمبكتي',
  'Riyadh Sharahili': 'رياض شراحيلي',
  'Nasser Al-Dawsari': 'ناصر الدوسري',

  // ── Iran ────────────────────────────────────────────────────────────────────
  'Mehdi Taremi': 'مهدي طارمي',
  'Sardar Azmoun': 'سردار أزمون',
  'Alireza Jahanbakhsh': 'عليرضا جهانبخش',
  'Milad Mohammadi': 'ميلاد محمدي',
  'Alireza Beiranvand': 'عليرضا بيرانوند',
  'Ali Gholizadeh': 'علي غوليزاده',
  'Saman Ghoddos': 'سامان قدوس',
  'Karim Ansarifard': 'كريم أنصاري فرد',

  // ── Australia ────────────────────────────────────────────────────────────────
  'Mathew Leckie': 'ماثيو ليكي',
  'Aaron Mooy': 'آرون موي',
  'Jackson Irvine': 'جاكسون إيرفين',
  'Riley McGree': 'رايلي ماكغري',
  'Mat Ryan': 'مات راين',
  'Mitchell Duke': 'ميتشيل ديوك',
  'Craig Goodwin': 'كريغ غودوين',
  'Martin Boyle': 'مارتن بويل',
  'Aziz Behich': 'عزيز بيهيش',
  'Keanu Baccus': 'كيانو باكوس',
  'Cameron Devlin': 'كاميرون ديفلن',

  // ── Switzerland ──────────────────────────────────────────────────────────────
  'Granit Xhaka': 'غرانيت تشاكا',
  'Xherdan Shaqiri': 'شيردان شاكيري',
  'Manuel Akanji': 'مانويل أكانجي',
  'Haris Seferovic': 'هاريس سيفيروفيتش',
  'Haris Seferović': 'هاريس سيفيروفيتش',
  'Yann Sommer': 'يان زومر',
  'Denis Zakaria': 'دينيس زاكاريا',
  'Breel Embolo': 'بريل إمبولو',
  'Noah Okafor': 'نوا أوكافور',
  'Dan Ndoye': 'دان ندوي',
  'Fabian Schar': 'فابيان شار',
  'Fabian Schär': 'فابيان شار',
  'Ricardo Rodriguez': 'ريكاردو رودريغيز',
  'Ricardo Rodríguez': 'ريكاردو رودريغيز',
  'Ruben Vargas': 'روبن فارغاس',
  'Michel Aebischer': 'ميشيل أيبيشر',
  'Gregor Kobel': 'غريغور كوبيل',
  'Silvan Widmer': 'سيلفان ويدمر',

  // ── Croatia ──────────────────────────────────────────────────────────────────
  'Luka Modric': 'لوكا مودريتش',
  'Luka Modrić': 'لوكا مودريتش',
  'Ivan Perisic': 'إيفان بيريشيتش',
  'Ivan Perišić': 'إيفان بيريشيتش',
  'Marcelo Brozovic': 'مارسيلو بروزوفيتش',
  'Marcelo Brozović': 'مارسيلو بروزوفيتش',
  'Mateo Kovacic': 'ماتيو كوفاتشيتش',
  'Mateo Kovačić': 'ماتيو كوفاتشيتش',
  'Josko Gvardiol': 'يوشكو غفارديول',
  'Joško Gvardiol': 'يوشكو غفارديول',
  'Josip Stanisic': 'يوسيب ستانيشيتش',
  'Josip Stanišić': 'يوسيب ستانيشيتش',
  'Dominik Livakovic': 'دومينيك ليفاكوفيتش',
  'Dominik Livaković': 'دومينيك ليفاكوفيتش',
  'Andrej Kramaric': 'أندريي كراماريتش',
  'Andrej Kramarić': 'أندريي كراماريتش',
  'Bruno Petkovic': 'برونو بيتكوفيتش',
  'Bruno Petković': 'برونو بيتكوفيتش',
  'Ivan Gvardiol': 'إيفان غفارديول',
  'Dejan Lovren': 'ديان لوفرن',
  'Borna Sosa': 'بورنا سوسا',
  'Mario Pasalic': 'ماريو باساليتش',
  'Mario Pašalić': 'ماريو باساليتش',

  // ── Serbia ───────────────────────────────────────────────────────────────────
  'Aleksandar Mitrovic': 'أليكساندر ميتروفيتش',
  'Aleksandar Mitrović': 'أليكساندر ميتروفيتش',
  'Nemanja Matic': 'نيمانيا ماتيتش',
  'Nemanja Matić': 'نيمانيا ماتيتش',
  'Sergej Milinkovic-Savic': 'سيرجيي ميلينكوفيتش سافيتش',
  'Sergej Milinković-Savić': 'سيرجيي ميلينكوفيتش سافيتش',
  'Nikola Milenkovic': 'نيكولا ميلينكوفيتش',
  'Nikola Milenković': 'نيكولا ميلينكوفيتش',
  'Predrag Rajkovic': 'بريدراغ رايكوفيتش',
  'Predrag Rajković': 'بريدراغ رايكوفيتش',
  'Dusan Tadic': 'دوشان تاديتش',
  'Dušan Tadić': 'دوشان تاديتش',
  'Dusan Vlahovic': 'دوشان فلاهوفيتش',
  'Dušan Vlahović': 'دوشان فلاهوفيتش',

  // ── Poland ───────────────────────────────────────────────────────────────────
  'Robert Lewandowski': 'روبرت ليفاندوفسكي',
  'Piotr Zielinski': 'بيوتر زيلينسكي',
  'Piotr Zieliński': 'بيوتر زيلينسكي',
  'Wojciech Szczesny': 'فويتشيخ شتشيسني',
  'Wojciech Szczęsny': 'فويتشيخ شتشيسني',
  'Kamil Glik': 'كاميل غليك',
  'Grzegorz Krychowiak': 'غجيغورز كريتشوفياك',
  'Arkadiusz Milik': 'أركاديوش ميليك',
  'Sebastian Szymanski': 'سيباستيان شيمانسكي',
  'Sebastian Szymański': 'سيباستيان شيمانسكي',

  // ── Denmark ──────────────────────────────────────────────────────────────────
  'Christian Eriksen': 'كريستيان إيريكسن',
  'Pierre-Emile Hojbjerg': 'بيير إيميل هوبيارغ',
  'Pierre-Emile Højbjerg': 'بيير إيميل هوبيارغ',
  'Kasper Schmeichel': 'كاسبر شمايكل',
  'Simon Kjaer': 'سيمون كيير',
  'Simon Kjær': 'سيمون كيير',
  'Andreas Christensen': 'أندرياس كريستنسن',
  'Mikkel Damsgaard': 'ميكيل دامسغارد',
  'Joakim Maehle': 'يواكيم مايلي',
  'Joakim Mæhle': 'يواكيم مايلي',
  'Rasmus Hojlund': 'راسموس هويلوند',
  'Rasmus Højlund': 'راسموس هويلوند',
  'Viktor Gyokeres': 'فيكتور غيوكيريش',

  // ── Turkey ───────────────────────────────────────────────────────────────────
  'Hakan Calhanoglu': 'هاكان تشالهانوغلو',
  'Hakan Çalhanoğlu': 'هاكان تشالهانوغلو',
  'Arda Guler': 'أردا غولر',
  'Arda Güler': 'أردا غولر',
  'Cengiz Under': 'جينغيز أوندر',
  'Cengiz Ünder': 'جينغيز أوندر',
  'Merih Demiral': 'ميريه ديميرال',
  'Yusuf Yazici': 'يوسف يازيجي',
  'Yusuf Yazıcı': 'يوسف يازيجي',
  'Kerem Akturkoglu': 'كيريم أكتوركوغلو',
  'Kerem Aktürkoğlu': 'كيريم أكتوركوغلو',
  'Ferdi Kadioglu': 'فيردي كاديوغلو',
  'Ferdi Kadıoğlu': 'فيردي كاديوغلو',
  'Calhanoglu': 'تشالهانوغلو',
  'Ugurcan Cakir': 'أوغورجان تشاكير',
  'Uğurcan Çakır': 'أوغورجان تشاكير',
  'Zeki Celik': 'زيكي تشيليك',
  'Zeki Çelik': 'زيكي تشيليك',

  // ── Nigeria ──────────────────────────────────────────────────────────────────
  'Victor Osimhen': 'فيكتور أوسيمهن',
  'Wilfried Ndidi': 'ويلفريد نديدي',
  'Alex Iwobi': 'أليكس إيووبي',
  'Ahmed Musa': 'أحمد موسى',
  'Kelechi Iheanacho': 'كيليتشي إيهيانا شو',
  'Samuel Chukwueze': 'صامويل تشوكويزي',
  'Terem Moffi': 'تيريم موفي',
  'Calvin Bassey': 'كالفين باسي',
  'Semi Ajayi': 'سيمي أجايي',
  'Joe Aribo': 'جو أريبو',
  'Uzoho Francis': 'أوزوهو فرانسيس',
  'Ola Aina': 'أولا عينا',
  'Ademola Lookman': 'أديمولا لوكمان',

  // ── Ivory Coast ───────────────────────────────────────────────────────────────
  'Wilfried Zaha': 'ويلفريد زاها',
  'Franck Kessie': 'فرانك كيسيه',
  'Franck Kessié': 'فرانك كيسيه',
  'Ibrahim Sangare': 'إبراهيم سانغاريه',
  'Ibrahim Sangaré': 'إبراهيم سانغاريه',
  'Sebastien Haller': 'سيباستيان هالر',
  'Sébastien Haller': 'سيباستيان هالر',
  'Eric Bailly': 'إيريك بايلي',
  'Nicolas Pepe': 'نيكولا بيبي',
  'Nicolas Pépé': 'نيكولا بيبي',
  'Simon Adingra': 'سيمون أدينغرا',
  'Odilon Kossounou': 'أوديلون كوسونو',
  'Oumar Diakite': 'عمر دياكيتي',
  'Alban Lafont': 'ألبان لافون',
  'Ousmane Diomande': 'عثمان ديومانده',
  'Ghislain Konan': 'غيسلان كونان',
  'Emmanuel Agbadou': 'إيمانويل أغبادو',
  'Wilfried Singo': 'ويلفريد سينغو',
  'Yan Diomande': 'يان ديومانده',
  'Guéla Doué': 'غيلا دوي',
  'Guela Doue': 'غيلا دوي',
  'Evan Ndicka': 'إيفان نديكا',
  'Bazoumana Toure': 'بازومانا توري',
  'Bazoumana Touré': 'بازومانا توري',
  'Jean Michael Seri': 'جان ميكائيل سيري',
  'Jean Michaël Seri': 'جان ميكائيل سيري',
  'Parfait Guiagon': 'بارفي غياغون',
  'Seko Fofana': 'سيكو فوفانا',
  'Yahia Fofana': 'يحيى فوفانا',
  'S. Fofana': 'سيكو فوفانا',
  'Elye Wahi': 'إيلي واهي',
  'Evann Guessand': 'إيفان غيسان',
  'Ange-Yoan Bonny': 'أنج-يوان بوني',
  'Christopher Operi': 'كريستوفر أوبيري',
  'Christ Inao Oulai': 'كريست إناو أولاي',
  'Christ Inao Oulaï': 'كريست إناو أولاي',
  'Amad Diallo': 'أماد ديالو',
  'A. Diallo': 'أماد ديالو',

  // ── Tunisia ──────────────────────────────────────────────────────────────────
  'Wahbi Khazri': 'وهبي الخزري',
  'Youssef Msakni': 'يوسف المساكني',
  'Hannibal Mejbri': 'هانيبال مجبري',
  'Anis Slimane': 'أنيس سليماني',
  'Ellyes Skhiri': 'إيليس الشخيري',
  'Montassar Talbi': 'منتصر الطلبي',
  'Nader Ghandri': 'نادر الغندري',
  'Dylan Bronn': 'ديلان برون',

  // ── Qatar ────────────────────────────────────────────────────────────────────
  'Akram Afif': 'أكرم عفيف',
  'Hassan Al-Haydos': 'حسن الهيدوس',
  'Almoez Ali': 'المعتز علي',
  'Abdelkarim Hassan': 'عبدالكريم حسن',
  'Bassam Al-Rawi': 'بسام الراوي',
  'Assim Madibo': 'عاصم ماديبو',
  'Pedro Miguel': 'بيدرو ميغيل',
  'Homam Ahmed': 'همام أحمد',
  'Mohammed Muntari': 'محمد منتاري',
  'Karim Boudiaf': 'كريم بوضياف',

  // ── Egypt ────────────────────────────────────────────────────────────────────
  'Mohamed Salah': 'محمد صلاح',
  'Mostafa Mohamed': 'مصطفى محمد',
  'Mahmoud Trezeguet': 'محمود تريزيغيه',
  'Omar Marmoush': 'عمر مرموش',
  'Zizo': 'زيزو',
  'Ahmed Sayed Zizo': 'أحمد سايد زيزو',
  'Amr Warda': 'عمرو وردة',
  'Hamdi Fathi': 'حمدي فتحي',
  'Ahmed Hegazi': 'أحمد حجازي',
  'Mohamed El-Shenawy': 'محمد الشناوي',
  'Akram Tawfik': 'أكرم توفيق',

  // ── Algeria ──────────────────────────────────────────────────────────────────
  'Riyad Mahrez': 'رياض محرز',
  'Islam Slimani': 'إسلام سليماني',
  'Ismail Bennacer': 'إسماعيل بن ناصر',
  'Ismaël Bennacer': 'إسماعيل بن ناصر',
  'Sofiane Feghouli': 'سفيان فغولي',
  'Said Benrahma': 'سعيد بن رحمة',
  'Saïd Benrahma': 'سعيد بن رحمة',
  'Youcef Atal': 'يوسف عطال',
  'Andy Delort': 'أندي ديلور',
  'Rais M\'Bolhi': 'رايس مبولحي',

  // ── Venezuela ────────────────────────────────────────────────────────────────
  'Salomon Rondon': 'سالومون روندون',
  'Salomón Rondón': 'سالومون روندون',
  'Jefferson Savarino': 'جيفيرسون سافارينو',
  'Yeferson Soteldo': 'ييفيرسون سوتيلدو',
  'Tomas Rincon': 'توماس رينكون',
  'Tomás Rincón': 'توماس رينكون',
  'Josef Martinez': 'يوسيف مارتينيز',
  'Josef Martínez': 'يوسيف مارتينيز',

  // ── Chile ────────────────────────────────────────────────────────────────────
  'Alexis Sanchez': 'أليكسيس سانتشيز',
  'Alexis Sánchez': 'أليكسيس سانتشيز',
  'Arturo Vidal': 'أرتورو فيدال',
  'Gary Medel': 'غاري ميديل',
  'Claudio Bravo': 'كلاوديو برافو',
  'Ben Brereton': 'بن بريرتون',
  'Erick Pulgar': 'إريك بولغار',
  'Charles Aranguiz': 'تشارلز أرانغويز',
  'Charles Aránguiz': 'تشارلز أرانغويز',

  // ── Peru ────────────────────────────────────────────────────────────────────
  'Paolo Guerrero': 'باولو غيريرو',
  'Gianluca Lapadula': 'جيانلوكا لابادولا',
  'Andre Carrillo': 'أندريه كاريلو',
  'André Carrillo': 'أندريه كاريلو',
  'Christian Cueva': 'كريستيان كويفا',
  'Pedro Gallese': 'بيدرو غالييسي',

  // ── Jordan ───────────────────────────────────────────────────────────────────
  'Jamal Sellami': 'جمال السلامي',
  // Exact keys as returned by api-football /players/squads
  'Yazid Abu Layla': 'يزيد أبو ليلى',
  'Abdallah Al Fakhouri': 'عبد الله الفاخوري',
  'Noureddin Zaid': 'نور الدين بني عطية',
  'H. Abu Al Dahab': 'حسام أبو الذهب',
  'M. Abu Hasheesh': 'محمد أبو حشيش',
  'M. Abualnadi': 'محمد أبو النادي',
  'Yazan Al Arab': 'يزن العرب',
  'Saed Al Rosan': 'سعد الروسان',
  'A. Badawi': 'أنس بدوي',
  'Abdallah Naseeb': 'عبد الله نصيب',
  'Saleem Obaid': 'سليم عبيد',
  'Ehsan Haddad': 'إحسان حداد',
  'Mohannad Abu Taha': 'مهند أبو طه',
  'M. Al Daoud': 'محمد الداوود',
  "Ibrahim Sa'deh": 'إبراهيم سعادة',
  'Nizar Al Rashdan': 'نزار الرشدان',
  'Noor Al Rawabdeh': 'نور الروابدة',
  'Rajaei Ayed': 'رجائي عايد',
  'Amer Jamous': 'عامر جاموس',
  'Mahmoud Al Mardi': 'محمود المرضي',
  'Mohammed Abu Zurayq': 'محمد أبو زريق',
  'O. Al Fakhouri': 'عودة الفاخوري',
  'A. Azaizeh': 'علي العزايزة',
  'Ali Olwan': 'علي علوان',
  'Ibrahim Sabra': 'إبراهيم صبرة',
  'Mousa Tamari': 'موسى التعمري',
  // Fallback spellings
  'Yazeed Abulaila': 'يزيد أبو ليلى',
  'Abdullah Al-Fakhouri': 'عبد الله الفاخوري',
  'Noureddin Bani Ateyah': 'نور الدين بني عطية',
  'Husam Abu Al-Dahab': 'حسام أبو الذهب',
  'Mohammad Abu Hashish': 'محمد أبو حشيش',
  'Mohammad Abu Al-Nadi': 'محمد أبو النادي',
  'Yazan Al-Arab': 'يزن العرب',
  'Saed Al-Rosan': 'سعد الروسان',
  'Anas Badawi': 'أنس بدوي',
  'Abdallah Nasib': 'عبد الله نصيب',
  'Saleem Obeid': 'سليم عبيد',
  'Mohammad Al-Dawood': 'محمد الداوود',
  'Ibrahim Sadeh': 'إبراهيم سعادة',
  'Nizar Al-Rashdan': 'نزار الرشدان',
  'Noor Al-Rawabdeh': 'نور الروابدة',
  'Mahmoud Mardi': 'محمود المرضي',
  'Mohammad Abu Zrayq': 'محمد أبو زريق',
  'Oudah Al-Fakhouri': 'عودة الفاخوري',
  'Ali Azayzeh': 'علي العزايزة',
  'Mousa Al-Tamari': 'موسى التعمري',

  // ── Iraq ─────────────────────────────────────────────────────────────────────
  // Goalkeepers
  'Ahmed Basil': 'أحمد باسل',
  'Aymen Hussein': 'أيمن حسين',
  'Ayman Hussein': 'أيمن حسين',
  'Jalal Hassan Hachim': 'جلال حسن',
  'Jalal Hassan': 'جلال حسن',
  // Defenders
  'Fahad Talib': 'فهد طالب',
  'Hussein Ali': 'حسين علي',
  'Merchas Doski': 'ميرخاس دوسكي',
  'Frans Putros': 'فرانس بطرس',
  'Zayed Tahseen': 'زيد تحسين',
  'Zaid Tahseen': 'زيد تحسين',
  'Amir Al Ammari': 'أمير العماري',
  'Amir Al-Ammari': 'أمير العماري',
  'Ali Al Hamadi': 'علي الحمادي',
  'Ali Al-Hamadi': 'علي الحمادي',
  // Midfielders
  'Rebin Solaka': 'ريبين سولاقا',
  'Rebin Sulaka': 'ريبين سولاقا',
  'Mustafa Saadoun': 'مصطفى سعدون',
  'Mustafa Saadoon': 'مصطفى سعدون',
  'Munaf Younus': 'مناف يونس',
  'Manaf Younis': 'مناف يونس',
  'Akam Rahman': 'أكام رحمان',
  'Zidane Iqbal': 'زيدان إقبال',
  'Kevin Yakob': 'كيفن يعقوب',
  'Kevin Yaqob': 'كيفن يعقوب',
  // Forwards / others
  'Ibraheem Bayesh': 'إبراهيم بايش',
  'Ibrahim Bayesh': 'إبراهيم بايش',
  'Youssef Amyn': 'يوسف أمين',
  'Yousef Amyn': 'يوسف أمين',
  'Aymen Hussain': 'أيمن حسين',
  'Marko Farji': 'ماركو فرجي',
  'Meme': 'ميمي',
  'Ahmed Qasem': 'أحمد قاسم',
  'Ahmad Qasim': 'أحمد قاسم',
  // Abbreviated-name fallbacks (used by tier-4 last-name lookup)
  'Ahmed Yahya': 'أحمد يحيى',
  'Zaid Ismaeel': 'زيد إسماعيل',
  'Aimar Sher': 'إيمار شير',
  'Ali Jasim': 'علي جاسم',
  'Ali Yousif Hashim': 'علي يوسف هاشم',

  // ── Saudi Arabia ──────────────────────────────────────────────────────────────
  // Exact API keys
  'Nawaf Al Aqidi': 'نواف العقيدي',
  'Ahmed Al Kassar': 'أحمد الكسار',
  'Mohammed Al Owais': 'محمد العويس',
  'Saud Abdulhamid': 'سعود عبد الحميد',
  'Mohammed Abu Al Shamat': 'محمد أبو الشامات',
  'Nawaf Boushal': 'نواف بوشل',
  'Abdulelah Al Amri': 'عبد الإله العمري',
  'Moteb Al Harbi': 'متعب الحربي',
  'Hassan Kadesh': 'حسان كادش',
  'Ali Lajami': 'علي لاجامي',
  'Ali Majrashi': 'علي مجرشي',
  'Hassan Tambakti': 'حسان تمبكتي',
  'Jehad Thakri': 'جهاد ذكري',
  'Nasser Al Dawsari': 'ناصر الدوسري',
  'Mohamed Kanno': 'محمد كنو',
  'Ziyad Al Johani': 'زياد الجهني',
  'Musab Al Juwayr': 'مصعب الجوير',
  'Abdullah Al Khaibari': 'عبد الله الخيبري',
  'Ala Al Haji': 'علاء الحجي',
  'Khalid Al Ghannam': 'خالد الغنام',
  'Sultan Mandash': 'سلطان مندش',
  'Ayman Yahya': 'أيمن يحيى',
  'Feras Al Brikan': 'فراس البريكان',
  'Abdullah Al Hamdan': 'عبد الله الحمدان',
  'Saleh Al Shehri': 'صالح الشهري',
  'Salem Al Dawsari': 'سالم الدوسري',
  // User-spelling variants
  'Nawaf Al-Aqidi': 'نواف العقيدي',
  'Ahmed Al-Kassar': 'أحمد الكسار',
  'Mohammed Abu Al-Shamat': 'محمد أبو الشامات',
  'Khalid Al-Ghannam': 'خالد الغنام',
  'Moteb Al-Harbi': 'متعب الحربي',
  'Jehad Thikri': 'جهاد ذكري',
  'Alaa Al-Hejji': 'علاء الحجي',
  'Ziyad Al-Johani': 'زياد الجهني',
  'Musab Al-Juwayr': 'مصعب الجوير',
  'Abdullah Al-Khaibari': 'عبد الله الخيبري',
  'Firas Al-Buraikan': 'فراس البريكان',

  // ── Qatar ─────────────────────────────────────────────────────────────────────
  'Julen Lopetegui': 'جولين لوبيتيغي',
  'J. Lopetegui': 'جولين لوبيتيغي',
  // Exact API keys
  'Mahmud Abunada': 'محمود أبو ندى',
  'Meshaal Barsham': 'مشعل برشم',
  'Salah Zakaria': 'صلاح زكريا',
  'Sultan Al Braik': 'سلطان البريك',
  'Jassem Gaber': 'جاسم جابر',
  'Boualem Khoukhi': 'بوعلام خوخي',
  'Lucas Mendes': 'لوكاس مينديز',
  'Ahmed Al Ganehi': 'أحمد الجانحي',
  'Abdulaziz Hatem': 'عبد العزيز حاتم',
  'Ahmed Fathi': 'أحمد فتحي',
  'Hassan Al Haydos': 'حسان الهيدوس',
  'Mohamed Al Manai': 'محمد المناعي',
  'Ahmed Alaa': 'أحمد علاء الدين',
  'Edmilson Junior': 'إدميلسون جونيور',
  'Tahsin Jamshid': 'تحسين محمد',
  // Abbreviated-name fallbacks (tier-4 last-name lookup)
  'Hashmi Al Hussain': 'الهاشمي الحسين',
  'Al-Hashmi Al-Hussain': 'الهاشمي الحسين',
  'Ayoub Al Oui': 'أيوب العلوي',
  'Ayoub Al Aloui': 'أيوب العلوي',
  'Issa Laye': 'عيسى لاي',
  'Yusuf Abdurisag': 'يوسف عبد الرزاق',
  // User-spelling variants
  'Mahmoud Abunada': 'محمود أبو ندى',
  'Sultan Al Brake': 'سلطان البريك',
  'Jassim Gaber': 'جاسم جابر',
  'Mohamed Al Mannai': 'محمد المناعي',
  'Ahmed Alaaeldin': 'أحمد علاء الدين',
  'Tahsin Mohammed': 'تحسين محمد',

  // ── Egypt ─────────────────────────────────────────────────────────────────────
  'Hossam Hassan': 'حسام حسن',
  'H. Hassan': 'هيثم حسن',
  // Exact API keys
  'Mohamed El Shenawy': 'محمد الشناوي',
  'Mostafa Shobeir': 'مصطفى شوبير',
  'Al Mahdi Soliman': 'المهدي سليمان',
  'Hossam Abdelmaguid': 'حسام عبد المجيد',
  'Mohamed Abdelmonem': 'محمد عبد المنعم',
  'Ahmed Fatouh': 'أحمد فتوح',
  'Karim Hafez': 'كريم حافظ',
  'Mohamed Hany': 'محمد هاني',
  'Yasser Ibrahim': 'ياسر إبراهيم',
  'Rami Rabia': 'رامي ربيعة',
  'M. Alaa': 'محمد علاء',
  'T. Alaa': 'طارق علاء',
  'Emam Ashour': 'إمام عاشور',
  'Marwan Attia': 'مروان عطية',
  'Nabil Emad Dunga': 'نبيل عماد',
  'Hamdi Fathy': 'حمدي فتحي',
  'Mohanad Lasheen': 'مهند لاشين',
  'Mahmoud Saber': 'محمود صابر',
  'Mostafa Zico': 'مصطفى زيكو',
  'Trézéguet': 'محمود حسن تريزيغيه',
  'Ahmed Zizo': 'أحمد سيد زيزو',
  'Ibrahim Adel': 'إبراهيم عادل',
  // Abbreviated-name fallbacks (tier-4 last-name lookup)
  'Hamza Abdelkarim': 'حمزة عبد الكريم',
  // User-spelling variants
  'El Mahdy Soliman': 'المهدي سليمان',
  'Ramy Rabia': 'رامي ربيعة',
  'Mohamed Alaa': 'محمد علاء',
  'Tarek Alaa': 'طارق علاء',
  'Mohannad Lasheen': 'مهند لاشين',
  'Mostafa Ziko': 'مصطفى زيكو',
  'Nabil Emad': 'نبيل عماد',
  'Mahmoud Hassan Trezeguet': 'محمود حسن تريزيغيه',
  'Haitham Hassan': 'هيثم حسن',

  // ── Algeria ───────────────────────────────────────────────────────────────────
  'Vladimir Petković': 'فلاديمير بيتكوفيتش',
  'Vladimir Petkovic': 'فلاديمير بيتكوفيتش',
  'V. Petkovic': 'فلاديمير بيتكوفيتش',
  // Full names — tier-4 LASTNAME index resolves all "X. Lastname" API abbreviations
  'Oussama Benbot': 'أسامة بن بوط',
  'Melvin Mastil': 'ميلفين ماستيل',
  'Luca Zidane': 'لوكا زيدان',
  'Achraf Abada': 'أشرف عبادة',
  'Rayan Ait-Nouri': 'ريان آيت نوري',
  'Zineddine Belaid': 'زين الدين بلعيد',
  'Rafik Belghali': 'رفيق بلغالي',
  'Ramy Bensebaini': 'رامي بن سبعيني',
  'Jaouen Hadjam': 'جاوين حاجم',
  'Aissa Mandi': 'عيسى ماندي',
  'Mohamed Amine Tougai': 'محمد أمين توغاي',
  'Houssem Aouar': 'حسام عوار',
  'Nabil Bentaleb': 'نبيل بن طالب',
  'Hicham Boudaoui': 'هشام بوداوي',
  'Ibrahim Maza': 'إبراهيم مازة',
  'Yacine Titraoui': 'ياسين تيطراوي',
  'Ramiz Zerrouki': 'رمضان زروقي',
  'Fares Chaibi': 'فارس شايبي',
  'Mohamed Amine Amoura': 'محمد أمين عمورة',
  'Ahmed Benbouali': 'أحمد بن بوعلي',
  'Adil Boulbina': 'عادل بولبينة',
  'Fares Ghedjemis': 'فارس غدجيميس',
  'Amine Gouiri': 'أمين غويري',
  'Anis Hadj-Moussa': 'أنيس حاج موسى',
  // Extra players from user JSON not in current API squad
  'Abdellatif Ramdane': 'عبد اللطيف رمضان',
  'Mehdi Dorval': 'مهدي دورفال',

  // ── Tunisia ───────────────────────────────────────────────────────────────────
  'Sabri Lamouchi': 'صبري لموشي',
  'S. Lamouchi': 'صبري لموشي',
  // Full names — tier-4 LASTNAME index resolves all "X. Lastname" API abbreviations
  'Aymen Dahmen': 'أيمن دحمان',
  'C. Abdelmouhib': 'عبد المهيب الشماخ',
  'Ali Abdi': 'علي العابدي',
  'Adem Arous': 'آدم العروس',
  'Mohamed Amine Ben Hmida': 'محمد أمين بن حميدة',
  'Moutaz Neffati': 'معتز النفاتي',
  'Omar Rekik': 'عمر الرقيق',
  'Raed Chikhaoui': 'رائد الشخاوي',
  'Yan Valery': 'يان فاليري',
  'Anis Ben Slimane': 'أنيس بن سليمان',
  'Elias Achouri': 'إلياس العاشوري',
  'Hadj Mahmoud': 'الحاج محمود',
  'Mortadha Ben Ouanes': 'مرتضى بن وناس',
  'Rani Khedira': 'راني خضيرة',
  'Elias Saad': 'إلياس سعد',
  'Firas Chaouat': 'فراس شواط',
  'Hazem Mastouri': 'حازم المستوري',
  'Ismaël Gharbi': 'إسماعيل الغربي',
  'Ismael Gharbi': 'إسماعيل الغربي',
  'Khalil Ayari': 'خليل العياري',
  'Rayan Elloumi': 'ريان اللومي',
  'Sebastian Tounekti': 'سيباستيان تونكتي',
  // Variants to cover API spelling differences
  'Sabri Ben Hsan': 'صبري بن حسين',
  'Sabri Ben Hessen': 'صبري بن حسين',
  'Mohamed Amine Ben Hamida': 'محمد أمين بن حميدة',
  'Abdelmouhib Chamakh': 'عبد المهيب الشماخ',

  // ── Sweden ───────────────────────────────────────────────────────────────────
  'Alexander Isak': 'ألكسندر إيساك',

  // ── Paraguay ─────────────────────────────────────────────────────────────────
  'Julio Enciso': 'خوليو إنسيسو',
  'Miguel Almiron': 'ميغيل ألميرون',
  'Miguel Almirón': 'ميغيل ألميرون',

  // ── Bosnia ───────────────────────────────────────────────────────────────────
  'Tarik Muharemovic': 'طارق محارموفيتش',
  'Tarik Muharemović': 'طارق محارموفيتش',

  // ── South Africa ─────────────────────────────────────────────────────────────
  'Teboho Mokoena': 'تيبوهو موكوينا',
  'Nkosinathi Sibisi': 'نكوسيناثي سيبيسي',
  'Thalente Mbatha': 'تاليني مباثا',
  'Siphephelo Sithole': 'سيفيفيلو سيثولي',
  'Themba Zwane': 'ثيمبا زوانه',

  // ── Morocco ───────────────────────────────────────────────────────────────────
  'M. Ouahbi': 'محمد وهبي',
  // Direct keys for conflict/reversed-name cases
  'C. Talbi': 'شمس الدين طالبي',
  'Gessime Yassine': 'ياسين جسيم',
  'Brahim Diaz': 'إبراهيم دياز',
  // Full names — tier-4 LASTNAME index resolves "X. Lastname" API abbreviations
  'Munir Mohamedi': 'منير المحمدي',
  'Ahmed Reda Tagnaouti': 'أحمد رضا التكناوتي',
  'Chadi Riad': 'شادي رياض',
  'Issa Diop': 'عيسى ديوب',
  'Anass Salah-Eddine': 'أنس صلاح الدين',
  'Zakaria El Ouahdi': 'زكرياء الواحدي',
  'Redouane Halhal': 'رضوان حلاحل',
  'Youssef Belammari': 'يوسف بلعمري',
  'Neil El Aynaoui': 'نيل العيناوي',
  'Bilal El Khannouss': 'بلال الخنوس',
  'Ismael Saibari': 'إسماعيل الصيباري',
  'Samir El Mourabet': 'سمير المرابط',
  'Ayyoub Bouaddi': 'أيوب بوعدي',
  'Ayoub El Kaabi': 'أيوب الكعبي',
  'Abdessamad Ezzalzouli': 'عبد الصمد الزلزولي',
  'Soufiane Rahimi': 'سفيان رحيمي',
  'Chemsdine Talbi': 'شمس الدين طالبي',
  'Chamseddine Talbi': 'شمس الدين طالبي',
  'Chems-Eddine Talbi': 'شمس الدين طالبي',
  'Yassine Gessime': 'ياسين جسيم',
  'Ayoub Amaimouni': 'أيوب أمعيموني',
  'Ayoube Amaimouni Echghouyab': 'أيوب أمعيموني',
  'Munir El Kajoui': 'منير الكاجوي',
  'Marwane Saadane': 'مروان سعدان',
  'Amine Sbai': 'أمين سباي',
  // Hyphen-vs-space variants for API inconsistency
  'Youssef En Nesyri': 'يوسف النصيري',
  'Anass Salah Eddine': 'أنس صلاح الدين',
  'Yahia Attiyat Allah': 'يحيى عطية الله',

};

const PLAYER_NAMES_AR_LOWER: Record<string, string> = Object.fromEntries(
  Object.entries(PLAYER_NAMES_AR).map(([k, v]) => [k.toLowerCase(), v])
);

function stripAccents(s: string): string {
  return s.normalize('NFD').replace(/[̀-ͯ]/g, '').toLowerCase();
}

const PLAYER_NAMES_AR_STRIPPED: Record<string, string> = Object.fromEntries(
  Object.entries(PLAYER_NAMES_AR).map(([k, v]) => [stripAccents(k), v])
);

// Last-name index: "messi" → "ليونيل ميسي"
// Handles abbreviated API names like "L. Messi" or just "Messi"
const PLAYER_NAMES_AR_LASTNAME: Record<string, string> = {};
for (const [key, value] of Object.entries(PLAYER_NAMES_AR)) {
  const words = stripAccents(key).trim().split(/\s+/);
  const last = words[words.length - 1];
  if (last && last.length > 2 && !PLAYER_NAMES_AR_LASTNAME[last]) {
    PLAYER_NAMES_AR_LASTNAME[last] = value;
  }
}

// Core last-name index: strips "al-" / "abu-" prefixes so "al-hamadi" and
// "hamadi" (from API "Al Hamadi") both resolve to the same Arabic name.
const PLAYER_NAMES_AR_CORE: Record<string, string> = {};
for (const [key, value] of Object.entries(PLAYER_NAMES_AR)) {
  const words = stripAccents(key).trim().split(/\s+/);
  const last = words[words.length - 1];
  const core = last.replace(/^(al|abu|bin|bani|ibn)-/, '');
  if (core && core.length > 3 && core !== last && !PLAYER_NAMES_AR_CORE[core]) {
    PLAYER_NAMES_AR_CORE[core] = value;
  }
}

// ─── Phonetic transliteration fallback ───────────────────────────────────────

const DIGRAPH_MAP: Record<string, string> = {
  sh: 'ش', ch: 'تش', ph: 'ف', gh: 'غ', kh: 'خ',
  dj: 'ج', tz: 'تز', ts: 'تس', qu: 'ك', ck: 'ك',
  th: 'ت', wh: 'و',
  oo: 'و', ou: 'و', au: 'او', aw: 'او',
  ai: 'اي', ay: 'اي', ei: 'ي', ey: 'اي',
  ee: 'ي', ie: 'ي', oi: 'وي', ea: 'ي', oa: 'وا', ue: 'و',
  ll: 'ل', rr: 'ر', ss: 'س', tt: 'ت', nn: 'ن',
  mm: 'م', bb: 'ب', ff: 'ف', pp: 'ب', dd: 'د', cc: 'ك',
};

const SINGLE_MAP: Record<string, string> = {
  a: 'ا', b: 'ب', c: 'ك', d: 'د', e: 'ي',
  f: 'ف', g: 'غ', h: 'ه', i: 'ي', j: 'ج',
  k: 'ك', l: 'ل', m: 'م', n: 'ن', o: 'و',
  p: 'ب', q: 'ك', r: 'ر', s: 'س', t: 'ت',
  u: 'و', v: 'ف', w: 'و', x: 'كس', y: 'ي', z: 'ز',
};

function transliterateWord(word: string): string {
  const s = stripAccents(word);
  if (!s || /^[a-z]\.$/.test(s)) return '';
  let result = '';
  let i = 0;
  while (i < s.length) {
    const two = s[i] + (s[i + 1] ?? '');
    const digraph = DIGRAPH_MAP[two];
    if (digraph !== undefined) {
      result += digraph;
      i += 2;
    } else {
      result += SINGLE_MAP[s[i]] ?? '';
      i++;
    }
  }
  return result;
}

function transliterateToArabic(englishName: string): string {
  const words = englishName.trim().split(/[\s\-]+/).filter(Boolean);
  const parts = words.map(transliterateWord).filter(Boolean);
  return parts.length > 0 ? parts.join(' ') : englishName;
}

// ─────────────────────────────────────────────────────────────────────────────

export function getPlayerNameAr(englishName: string): string {
  if (!englishName) return englishName;

  // Tier 1-3: exact / lowercase / accent-stripped full-name lookup
  const direct =
    PLAYER_NAMES_AR[englishName] ??
    PLAYER_NAMES_AR_LOWER[englishName.toLowerCase()] ??
    PLAYER_NAMES_AR_STRIPPED[stripAccents(englishName)];
  if (direct) return direct;

  // Tier 4: last-name lookup — handles "Messi" or "L. Messi" → "ليونيل ميسي"
  const inputWords = englishName.trim().split(/\s+/);
  const lastWord = stripAccents(inputWords[inputWords.length - 1]);
  if (lastWord.length > 2) {
    const byLast = PLAYER_NAMES_AR_LASTNAME[lastWord];
    if (byLast) return byLast;
  }

  // Tier 4b: core last-name — "Al Hamadi" (space) matches "Al-Hamadi" (hyphen)
  // by stripping the al-/abu- prefix and looking up the bare root word
  if (lastWord.length > 3) {
    const coreWord = lastWord.replace(/^(al|abu|bin|bani|ibn)-/, '');
    if (coreWord !== lastWord) {
      const byCore = PLAYER_NAMES_AR_CORE[coreWord];
      if (byCore) return byCore;
    }
    // Also try the last word itself as a core key (handles "Al Hamadi" → "hamadi")
    const byCore = PLAYER_NAMES_AR_CORE[lastWord];
    if (byCore) return byCore;
  }

  // Tier 4c: abbreviated-name bridge
  // Stats API returns "Saleh Al-Shehri" but dict has "S. Al-Shehri" (from squad API).
  // Build abbreviated form and retry tiers 1-3.
  if (inputWords.length >= 2 && !/\.$/.test(inputWords[0])) {
    const abbrev = inputWords[0][0].toUpperCase() + '. ' + inputWords.slice(1).join(' ');
    const byAbbrev =
      PLAYER_NAMES_AR[abbrev] ??
      PLAYER_NAMES_AR_LOWER[abbrev.toLowerCase()] ??
      PLAYER_NAMES_AR_STRIPPED[stripAccents(abbrev)];
    if (byAbbrev) return byAbbrev;

    // Also try with last two words abbreviated: "Ahmed El Yamiq" → "A. El Yamiq"
    // and without the middle name: "Mohammed Khalil Ahmed" → "M. Ahmed"
    if (inputWords.length >= 3) {
      const abbrevLast = inputWords[0][0].toUpperCase() + '. ' + inputWords[inputWords.length - 1];
      const byAbbrevLast =
        PLAYER_NAMES_AR[abbrevLast] ??
        PLAYER_NAMES_AR_LOWER[abbrevLast.toLowerCase()] ??
        PLAYER_NAMES_AR_STRIPPED[stripAccents(abbrevLast)];
      if (byAbbrevLast) return byAbbrevLast;
    }
  }

  // Tier 5: phonetic transliteration — covers any player not in the dictionary
  return transliterateToArabic(englishName);
}
