// Arabic display names keyed by the English name returned by api-football
export const TEAM_NAMES_AR: Record<string, string> = {

  // ── Americas (CONMEBOL) ───────────────────────────────────────────────────
  'Argentina': 'الأرجنتين',
  'Brazil': 'البرازيل',
  'Colombia': 'كولومبيا',
  'Ecuador': 'الإكوادور',
  'Uruguay': 'أوروغواي',
  'Venezuela': 'فنزويلا',
  'Chile': 'تشيلي',
  'Peru': 'بيرو',
  'Paraguay': 'باراغواي',
  'Bolivia': 'بوليفيا',

  // ── Americas (CONCACAF) ──────────────────────────────────────────────────
  'United States': 'الولايات المتحدة',
  'USA': 'الولايات المتحدة',
  'Mexico': 'المكسيك',
  'Canada': 'كندا',
  'Panama': 'بنما',
  'Honduras': 'هندوراس',
  'Jamaica': 'جامايكا',
  'Costa Rica': 'كوستاريكا',
  'Trinidad and Tobago': 'ترينيداد وتوباغو',
  'El Salvador': 'السلفادور',
  'Guatemala': 'غواتيمالا',
  'Haiti': 'هايتي',
  'Cuba': 'كوبا',
  'Dominican Republic': 'جمهورية الدومينيكان',
  'Curacao': 'كوراساو',
  'Curaçao': 'كوراساو',
  'Suriname': 'سورينام',
  'Guyana': 'غيانا',
  'Barbados': 'باربادوس',
  'Belize': 'بليز',
  'Nicaragua': 'نيكاراغوا',

  // ── Europe (UEFA) ────────────────────────────────────────────────────────
  'France': 'فرنسا',
  'Spain': 'إسبانيا',
  'Germany': 'ألمانيا',
  'England': 'إنجلترا',
  'Portugal': 'البرتغال',
  'Netherlands': 'هولندا',
  'Belgium': 'بلجيكا',
  'Italy': 'إيطاليا',
  'Croatia': 'كرواتيا',
  'Denmark': 'الدنمارك',
  'Austria': 'النمسا',
  'Switzerland': 'سويسرا',
  'Serbia': 'صربيا',
  'Poland': 'بولندا',
  'Turkey': 'تركيا',
  'Türkiye': 'تركيا',
  'Ukraine': 'أوكرانيا',
  'Scotland': 'اسكتلندا',
  'Romania': 'رومانيا',
  'Hungary': 'المجر',
  'Greece': 'اليونان',
  'Slovakia': 'سلوفاكيا',
  'Slovenia': 'سلوفينيا',
  'Albania': 'ألبانيا',
  'Wales': 'ويلز',
  'Norway': 'النرويج',
  'Sweden': 'السويد',
  'Finland': 'فنلندا',
  'Iceland': 'آيسلندا',
  'Ireland': 'أيرلندا',
  'Republic of Ireland': 'جمهورية أيرلندا',
  'Northern Ireland': 'أيرلندا الشمالية',
  'Bosnia and Herzegovina': 'البوسنة والهرسك',
  'Bosnia & Herzegovina': 'البوسنة والهرسك',
  'Bosnia': 'البوسنة',
  'Montenegro': 'الجبل الأسود',
  'North Macedonia': 'مقدونيا الشمالية',
  'Georgia': 'جورجيا',
  'Israel': 'إسرائيل',
  'Bulgaria': 'بلغاريا',
  'Belarus': 'بيلاروسيا',
  'Kosovo': 'كوسوفو',
  'Armenia': 'أرمينيا',
  'Azerbaijan': 'أذربيجان',
  'Luxembourg': 'لوكسمبورغ',
  'Moldova': 'مولدوفا',
  'Estonia': 'إستونيا',
  'Latvia': 'لاتفيا',
  'Lithuania': 'ليتوانيا',
  'Kazakhstan': 'كازاخستان',
  'Czech Republic': 'التشيك',
  'Czechia': 'التشيك',
  'Russia': 'روسيا',

  // ── Asia (AFC) ────────────────────────────────────────────────────────────
  'Japan': 'اليابان',
  'South Korea': 'كوريا الجنوبية',
  'Korea Republic': 'كوريا الجنوبية',
  'Republic of Korea': 'كوريا الجنوبية',
  'North Korea': 'كوريا الشمالية',
  'DPR Korea': 'كوريا الشمالية',
  'Australia': 'أستراليا',
  'Iran': 'إيران',
  'Saudi Arabia': 'المملكة العربية السعودية',
  'Jordan': 'الأردن',
  'Uzbekistan': 'أوزبكستان',
  'China': 'الصين',
  'China PR': 'الصين',
  'Qatar': 'قطر',
  'Bahrain': 'البحرين',
  'Iraq': 'العراق',
  'United Arab Emirates': 'الإمارات العربية المتحدة',
  'UAE': 'الإمارات العربية المتحدة',
  'Kuwait': 'الكويت',
  'Oman': 'عُمان',
  'Indonesia': 'إندونيسيا',
  'Thailand': 'تايلاند',
  'Vietnam': 'فيتنام',
  'Philippines': 'الفلبين',
  'Malaysia': 'ماليزيا',
  'India': 'الهند',
  'Kyrgyzstan': 'قيرغيزستان',
  'Tajikistan': 'طاجيكستان',
  'Turkmenistan': 'تركمانستان',
  'Afghanistan': 'أفغانستان',
  'Pakistan': 'باكستان',
  'Bangladesh': 'بنغلاديش',
  'Nepal': 'نيبال',
  'Sri Lanka': 'سريلانكا',
  'Lebanon': 'لبنان',
  'Syria': 'سوريا',
  'Yemen': 'اليمن',
  'Palestine': 'فلسطين',
  'Myanmar': 'ميانمار',
  'Cambodia': 'كمبوديا',
  'Singapore': 'سنغافورة',
  'Hong Kong': 'هونج كونج',
  'Mongolia': 'منغوليا',
  'Chinese Taipei': 'تايبيه الصيني',
  'Maldives': 'المالديف',
  'Timor-Leste': 'تيمور الشرقية',

  // ── Africa (CAF) ─────────────────────────────────────────────────────────
  'Morocco': 'المغرب',
  'Senegal': 'السنغال',
  'Nigeria': 'نيجيريا',
  'South Africa': 'جنوب أفريقيا',
  'Egypt': 'مصر',
  'Algeria': 'الجزائر',
  'Tunisia': 'تونس',
  'Mali': 'مالي',
  'Cameroon': 'الكاميرون',
  'Ghana': 'غانا',
  "Ivory Coast": 'كوت ديفوار',
  "Côte d'Ivoire": 'كوت ديفوار',
  "Cote d'Ivoire": 'كوت ديفوار',
  'DR Congo': 'جمهورية الكونغو الديمقراطية',
  'Democratic Republic of Congo': 'جمهورية الكونغو الديمقراطية',
  'Congo DR': 'جمهورية الكونغو الديمقراطية',
  'Tanzania': 'تنزانيا',
  'Zambia': 'زامبيا',
  'Burkina Faso': 'بوركينا فاسو',
  'Uganda': 'أوغندا',
  'Kenya': 'كينيا',
  'Angola': 'أنغولا',
  'Mozambique': 'موزمبيق',
  'Zimbabwe': 'زيمبابوي',
  'Gambia': 'غامبيا',
  'Guinea': 'غينيا',
  'Guinea-Bissau': 'غينيا بيساو',
  'Equatorial Guinea': 'غينيا الاستوائية',
  'Sierra Leone': 'سيراليون',
  'Liberia': 'ليبيريا',
  'Sudan': 'السودان',
  'Libya': 'ليبيا',
  'Mauritania': 'موريتانيا',
  'Cape Verde': 'الرأس الأخضر',
  'Cabo Verde': 'الرأس الأخضر',
  'Cape Verde Islands': 'الرأس الأخضر',
  'Benin': 'بنين',
  'Togo': 'توغو',
  'Congo': 'الكونغو',
  'Rwanda': 'رواندا',
  'Comoros': 'جزر القمر',
  'Ethiopia': 'إثيوبيا',
  'Namibia': 'ناميبيا',
  'Botswana': 'بوتسوانا',
  'Madagascar': 'مدغشقر',
  'Niger': 'النيجر',
  'Chad': 'تشاد',

  // ── Oceania (OFC) ─────────────────────────────────────────────────────────
  'New Zealand': 'نيوزيلندا',
  'Fiji': 'فيجي',
  'Papua New Guinea': 'بابوا غينيا الجديدة',
  'Solomon Islands': 'جزر سليمان',
  'Vanuatu': 'فانواتو',
  'New Caledonia': 'كاليدونيا الجديدة',
  'Tahiti': 'تاهيتي',
  'Samoa': 'ساموا',
  'Tonga': 'تونغا',
  'Cook Islands': 'جزر كوك',
};

const TEAM_NAMES_AR_LOWER: Record<string, string> = Object.fromEntries(
  Object.entries(TEAM_NAMES_AR).map(([k, v]) => [k.toLowerCase(), v])
);

export function getTeamNameAr(englishName: string): string {
  return TEAM_NAMES_AR[englishName] ?? TEAM_NAMES_AR_LOWER[englishName.toLowerCase()] ?? englishName;
}
